/**
 * 2025-2026 çalışma takvimi ve Coğrafya 9. sınıf yıllık plan içeriği ekler (deneme için).
 * Kullanım: cd backend && npm run seed-work-calendar
 */

import 'dotenv/config';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { WorkCalendar } from '../src/work-calendar/entities/work-calendar.entity';
import { YillikPlanIcerik } from '../src/yillik-plan-icerik/entities/yillik-plan-icerik.entity';

const ACADEMIC_YEAR = '2025-2026';

// MEB 2025-2026 resmi çalışma takvimi (8 Eylül 2025 - 26 Haziran 2026)
// 1.dönem: 8 Eylül - 16 Ocak | Ara tatil: 10-14 Kasım | Yarıyıl: 19-30 Ocak
// 2.dönem: 2 Şubat - 26 Haziran | Ara tatil: 16-20 Mart
const WORK_CALENDAR: Omit<WorkCalendar, 'id' | 'createdAt' | 'updatedAt'>[] = [
  { academicYear: ACADEMIC_YEAR, weekOrder: 1, weekStart: '2025-09-08', weekEnd: '2025-09-12', ay: 'EYLÜL', haftaLabel: '1. Hafta: 8-12 Eylül', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 1 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 2, weekStart: '2025-09-15', weekEnd: '2025-09-19', ay: 'EYLÜL', haftaLabel: '2. Hafta: 15-19 Eylül', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 2 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 3, weekStart: '2025-09-22', weekEnd: '2025-09-26', ay: 'EYLÜL', haftaLabel: '3. Hafta: 22-26 Eylül', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 3 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 4, weekStart: '2025-09-29', weekEnd: '2025-10-03', ay: 'EKİM', haftaLabel: '4. Hafta: 29 Eylül - 3 Ekim', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 4 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 5, weekStart: '2025-10-06', weekEnd: '2025-10-10', ay: 'EKİM', haftaLabel: '5. Hafta: 6-10 Ekim', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 5 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 6, weekStart: '2025-10-13', weekEnd: '2025-10-17', ay: 'EKİM', haftaLabel: '6. Hafta: 13-17 Ekim', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 6 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 7, weekStart: '2025-10-20', weekEnd: '2025-10-24', ay: 'EKİM', haftaLabel: '7. Hafta: 20-24 Ekim', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 7 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 8, weekStart: '2025-10-27', weekEnd: '2025-10-31', ay: 'EKİM', haftaLabel: '8. Hafta: 27-31 Ekim (Sınav)', isTatil: false, tatilLabel: null, sinavEtiketleri: '1. Dönem 1. Sınav haftası', sortOrder: 8 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 9, weekStart: '2025-11-03', weekEnd: '2025-11-07', ay: 'KASIM', haftaLabel: '9. Hafta: 3-7 Kasım', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 9 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 0, weekStart: '2025-11-10', weekEnd: '2025-11-14', ay: 'KASIM', haftaLabel: null, isTatil: true, tatilLabel: '1. DÖNEM ARA TATİLİ: 10-14 Kasım', sinavEtiketleri: null, sortOrder: 10 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 10, weekStart: '2025-11-17', weekEnd: '2025-11-21', ay: 'KASIM', haftaLabel: '10. Hafta: 17-21 Kasım', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 11 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 11, weekStart: '2025-11-24', weekEnd: '2025-11-28', ay: 'KASIM', haftaLabel: '11. Hafta: 24-28 Kasım', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 12 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 12, weekStart: '2025-12-01', weekEnd: '2025-12-05', ay: 'ARALIK', haftaLabel: '12. Hafta: 1-5 Aralık', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 13 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 13, weekStart: '2025-12-08', weekEnd: '2025-12-12', ay: 'ARALIK', haftaLabel: '13. Hafta: 8-12 Aralık', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 14 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 14, weekStart: '2025-12-15', weekEnd: '2025-12-19', ay: 'ARALIK', haftaLabel: '14. Hafta: 15-19 Aralık', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 15 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 15, weekStart: '2025-12-22', weekEnd: '2025-12-26', ay: 'ARALIK', haftaLabel: '15. Hafta: 22-26 Aralık', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 16 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 16, weekStart: '2025-12-29', weekEnd: '2026-01-02', ay: 'OCAK', haftaLabel: '16. Hafta: 29 Aralık - 2 Ocak', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 17 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 17, weekStart: '2026-01-05', weekEnd: '2026-01-09', ay: 'OCAK', haftaLabel: '17. Hafta: 5-9 Ocak', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 18 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 18, weekStart: '2026-01-12', weekEnd: '2026-01-16', ay: 'OCAK', haftaLabel: '18. Hafta: 12-16 Ocak', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 19 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 0, weekStart: '2026-01-19', weekEnd: '2026-01-30', ay: 'OCAK', haftaLabel: null, isTatil: true, tatilLabel: 'YARIYIL TATİLİ: 19-30 Ocak', sinavEtiketleri: null, sortOrder: 20 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 19, weekStart: '2026-02-02', weekEnd: '2026-02-06', ay: 'ŞUBAT', haftaLabel: '19. Hafta: 2-6 Şubat', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 21 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 20, weekStart: '2026-02-09', weekEnd: '2026-02-13', ay: 'ŞUBAT', haftaLabel: '20. Hafta: 9-13 Şubat', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 22 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 21, weekStart: '2026-02-16', weekEnd: '2026-02-20', ay: 'ŞUBAT', haftaLabel: '21. Hafta: 16-20 Şubat', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 23 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 22, weekStart: '2026-02-23', weekEnd: '2026-02-27', ay: 'ŞUBAT', haftaLabel: '22. Hafta: 23-27 Şubat', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 24 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 23, weekStart: '2026-03-02', weekEnd: '2026-03-06', ay: 'MART', haftaLabel: '23. Hafta: 2-6 Mart', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 25 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 24, weekStart: '2026-03-09', weekEnd: '2026-03-13', ay: 'MART', haftaLabel: '24. Hafta: 9-13 Mart', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 26 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 0, weekStart: '2026-03-16', weekEnd: '2026-03-20', ay: 'MART', haftaLabel: null, isTatil: true, tatilLabel: '2. DÖNEM ARA TATİLİ: 16-20 Mart', sinavEtiketleri: null, sortOrder: 27 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 25, weekStart: '2026-03-23', weekEnd: '2026-03-27', ay: 'MART', haftaLabel: '25. Hafta: 23-27 Mart', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 28 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 26, weekStart: '2026-03-30', weekEnd: '2026-04-03', ay: 'NİSAN', haftaLabel: '26. Hafta: 30 Mart - 3 Nisan', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 29 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 27, weekStart: '2026-04-06', weekEnd: '2026-04-10', ay: 'NİSAN', haftaLabel: '27. Hafta: 6-10 Nisan', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 30 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 28, weekStart: '2026-04-13', weekEnd: '2026-04-17', ay: 'NİSAN', haftaLabel: '28. Hafta: 13-17 Nisan', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 31 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 29, weekStart: '2026-04-20', weekEnd: '2026-04-24', ay: 'NİSAN', haftaLabel: '29. Hafta: 20-24 Nisan', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 32 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 30, weekStart: '2026-04-27', weekEnd: '2026-05-01', ay: 'MAYIS', haftaLabel: '30. Hafta: 27 Nisan - 1 Mayıs', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 33 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 31, weekStart: '2026-05-04', weekEnd: '2026-05-08', ay: 'MAYIS', haftaLabel: '31. Hafta: 4-8 Mayıs', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 34 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 32, weekStart: '2026-05-11', weekEnd: '2026-05-15', ay: 'MAYIS', haftaLabel: '32. Hafta: 11-15 Mayıs', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 35 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 33, weekStart: '2026-05-18', weekEnd: '2026-05-22', ay: 'MAYIS', haftaLabel: '33. Hafta: 18-22 Mayıs', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 36 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 34, weekStart: '2026-05-25', weekEnd: '2026-05-29', ay: 'MAYIS', haftaLabel: '34. Hafta: 25-29 Mayıs', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 37 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 35, weekStart: '2026-06-15', weekEnd: '2026-06-19', ay: 'HAZİRAN', haftaLabel: '35. Hafta: 15-19 Haziran', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 38 },
  { academicYear: ACADEMIC_YEAR, weekOrder: 36, weekStart: '2026-06-22', weekEnd: '2026-06-26', ay: 'HAZİRAN', haftaLabel: '36. Hafta: 22-26 Haziran', isTatil: false, tatilLabel: null, sinavEtiketleri: null, sortOrder: 39 },
];

// Coğrafya 9. sınıf örnek plan içeriği – örnek plan yapısına uygun (ÜNİTE/TEMA, COĞ.9.x.x, Belirli Gün)
type PlanIcerikSeedItem = Omit<
  YillikPlanIcerik,
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'olcmeDegerlendirme'
  | 'sosyalDuygusal'
  | 'degerler'
  | 'okuryazarlikBecerileri'
  | 'zenginlestirme'
  | 'okulTemelliPlanlama'
> &
  Partial<
    Pick<
      YillikPlanIcerik,
      | 'olcmeDegerlendirme'
      | 'sosyalDuygusal'
      | 'degerler'
      | 'okuryazarlikBecerileri'
      | 'zenginlestirme'
      | 'okulTemelliPlanlama'
    >
  >;
const PLAN_ICERIK: PlanIcerikSeedItem[] = [
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 1,
    unite: 'COĞRAFYANIN DOĞASI',
    konu: 'Coğrafya Biliminin Konusu ve Bölümleri',
    kazanimlar:
      'COĞ.9.1.1. Coğrafya biliminin konusu ve bölümlerini çözümleyebilme\na) Coğrafya biliminin konusu ve bölümlerini oluşturan bileşenleri belirler.\nb) Bileşenler arasındaki ilişkileri belirler.',
    dersSaati: 2,
    belirliGunHaftalar: '15 Temmuz Demokrasi ve Millî Birlik Günü',
    surecBilesenleri: 'DB1.1. Kendini Tanıma, SDB1.2. Kendini Düzenleme, SDB2.1. İletişim, SDB2.2. İş Birliği',
    olcmeDegerlendirme: 'Öğretmen gözlemi, öz değerlendirme, akran değerlendirme',
    sosyalDuygusal: 'SDB1.2 Kendini Düzenleme',
    degerler: 'Bilimsellik, sorumluluk',
    okuryazarlikBecerileri: 'Metin okuma, görsel okuma',
    zenginlestirme: 'Günlük hayattan coğrafi örnekler',
    okulTemelliPlanlama: 'Sınıf içi tartışma',
    sortOrder: 1,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 2,
    unite: 'COĞRAFYANIN DOĞASI',
    konu: 'Niçin Coğrafya Öğrenmeliyiz?',
    kazanimlar:
      'COĞ.9.1.2. Mekânsal düşünme ile coğrafya öğrenmenin önemini çözümleyebilme\na) Mekânda gerçekleşen coğrafi olay, olgu veya konuyu belirler.\nb) Coğrafya öğrenmenin önemi arasındaki ilişkiyi belirler.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Öğretmen gözlemi, sözlü sunum',
    sosyalDuygusal: 'SDB2.1. İletişim, SDB2.2. İş Birliği',
    degerler: 'Bilimsellik, merak',
    okuryazarlikBecerileri: 'Mekânsal okuryazarlık',
    zenginlestirme: 'Mekân- olay ilişkisi haritası',
    okulTemelliPlanlama: 'Grup çalışması',
    sortOrder: 2,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 3,
    unite: 'COĞRAFYANIN DOĞASI',
    konu: 'Coğrafya Biliminin Gelişimi',
    kazanimlar:
      'COĞ.9.1.3. Coğrafya biliminin gelişimi hakkında bilgi toplayabilme\na) Gerekli bilgilere ulaşmak için kullanacağı araçları belirler.\nb) Bilgileri doğrular ve kaydeder.',
    dersSaati: 2,
    belirliGunHaftalar: '27 Eylül Dünya Turizm Günü',
    surecBilesenleri: 'DB2.1. Araştırma, SDB1.2. Kendini Düzenleme',
    olcmeDegerlendirme: 'Araştırma raporu, öz değerlendirme',
    sosyalDuygusal: 'SDB1.2. Kendini Düzenleme',
    degerler: 'Bilimsellik, özgünlük',
    okuryazarlikBecerileri: 'Metin okuma, dijital okuryazarlık',
    zenginlestirme: 'Coğrafya tarihi araştırması',
    okulTemelliPlanlama: 'Kütüphane / dijital kaynak kullanımı',
    sortOrder: 3,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 4,
    unite: 'MEKÂNSAL BİLGİ TEKNOLOJİLERİ',
    konu: 'Mekânın Aynası Haritalar',
    kazanimlar:
      'COĞ.9.2.1. Harita uygulamaları yapabilme\na) Haritaya ait bileşenlerden yararlanarak haritaları okur.\nb) Haritadaki olay, olgu ve mekânlar arası ilişkileri çözümler.\nç) Harita yapım aşamalarını kullanarak harita oluşturur.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Harita okuma uygulaması, performans görevi',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Dikkat, özen',
    okuryazarlikBecerileri: 'Görsel okuma, harita okuryazarlığı',
    zenginlestirme: 'Basit harita çizimi',
    okulTemelliPlanlama: 'Harita atölyesi',
    sortOrder: 4,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 5,
    unite: 'MEKÂNSAL BİLGİ TEKNOLOJİLERİ',
    konu: 'Mekânın Aynası Haritalar',
    kazanimlar:
      'COĞ.9.2.1. Harita uygulamaları yapabilme\na) Haritaya ait bileşenlerden yararlanarak haritaları okur.\nb) Haritadaki olay, olgu ve mekânlar arası ilişkileri çözümler.',
    dersSaati: 2,
    belirliGunHaftalar: '4 Ekim Hayvanları Koruma Günü',
    surecBilesenleri: 'DB2.2. Yaratıcı Düşünme, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Harita yorumlama, akran değerlendirme',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Çevre bilinci, sorumluluk',
    okuryazarlikBecerileri: 'Görsel okuma, mekânsal okuryazarlık',
    zenginlestirme: 'Farklı ölçekli harita karşılaştırma',
    okulTemelliPlanlama: 'Çevre / doğa temalı etkinlik',
    sortOrder: 5,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 6,
    unite: 'MEKÂNSAL BİLGİ TEKNOLOJİLERİ',
    konu: "Türkiye'nin Coğrafi Konumu",
    kazanimlar:
      "COĞ.9.2.2. Türkiye'nin konum özelliklerini algılayabilme\na) Türkiye'nin konum özelliklerini belirler.\nb) Konum özelliklerini görselleştirir.\nc) Konum özelliklerini özetler.",
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, DB2.1. Araştırma',
    olcmeDegerlendirme: 'Konum haritası çizimi, öğretmen gözlemi',
    sosyalDuygusal: 'SDB3.1. Empati',
    degerler: 'Vatan sevgisi, bilimsellik',
    okuryazarlikBecerileri: 'Harita okuryazarlığı, görsel okuma',
    zenginlestirme: 'Türkiye konum sunumu',
    okulTemelliPlanlama: 'Atlas / GIS uygulaması',
    sortOrder: 6,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 7,
    unite: 'MEKÂNSAL BİLGİ TEKNOLOJİLERİ',
    konu: 'Mekânsal Bilgi Teknolojilerinin Bileşenleri',
    kazanimlar:
      'COĞ.9.2.3. Mekânsal bilgi teknolojilerini oluşturan bileşenleri çözümleyebilme\na) Bileşenleri belirler.\nb) Bileşenler arasındaki ilişkileri belirler.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.2. İş Birliği',
    olcmeDegerlendirme: 'Sunum, kavram haritası',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Dijital okuryazarlık, etik kullanım',
    okuryazarlikBecerileri: 'Dijital okuryazarlık, teknoloji okuryazarlığı',
    zenginlestirme: 'CBS / uydu görüntüsü inceleme',
    okulTemelliPlanlama: 'Bilgisayar laboratuvarı etkinliği',
    sortOrder: 7,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 8,
    unite: null,
    konu: 'SINAV HAFTASI',
    kazanimlar: null,
    dersSaati: 1,
    belirliGunHaftalar: 'Cumhuriyet Bayramı (29 Ekim)',
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: '1. dönem ara sınavı',
    sosyalDuygusal: 'SDB1.2. Kendini Düzenleme',
    degerler: 'Dürüstlük, sorumluluk',
    okuryazarlikBecerileri: 'Sınav okuryazarlığı',
    zenginlestirme: null,
    okulTemelliPlanlama: 'Sınav uygulaması',
    sortOrder: 8,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 9,
    unite: 'DOĞAL SİSTEMLER VE SÜREÇLER',
    konu: 'Hava Olayları ve Günlük Hayata Etkileri',
    kazanimlar:
      'COĞ.9.3.1. Hava olaylarını günlük hayatla ilişkilendirebilme\na) Hava olaylarını tanımlar.\nb) Hava olaylarının günlük hayata etkilerini değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB1.2. Kendini Düzenleme',
    olcmeDegerlendirme: 'Gözlem formu, öğretmen gözlemi',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Çevre bilinci, sorumluluk',
    okuryazarlikBecerileri: 'Veri okuma, meteoroloji okuryazarlığı',
    zenginlestirme: 'Hava durumu takip projesi',
    okulTemelliPlanlama: 'Hava gözlemi etkinliği',
    sortOrder: 9,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 10,
    unite: 'DOĞAL SİSTEMLER VE SÜREÇLER',
    konu: 'İklim Elemanları',
    kazanimlar:
      'COĞ.9.3.2. İklim elemanlarını analiz edebilme\na) İklim elemanlarını belirler.\nb) İklim elemanları arasındaki ilişkileri açıklar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, DB2.1. Araştırma',
    olcmeDegerlendirme: 'Kavram haritası, performans görevi',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Bilimsellik, dikkat',
    okuryazarlikBecerileri: 'Grafik okuma, tablo yorumlama',
    zenginlestirme: 'İklim grafiği çizimi',
    okulTemelliPlanlama: 'İklim verisi analizi',
    sortOrder: 10,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 11,
    unite: 'DOĞAL SİSTEMLER VE SÜREÇLER',
    konu: 'Türkiye İklimi',
    kazanimlar:
      'COĞ.9.3.3. Türkiye iklimini değerlendirebilme\na) Türkiye iklim tiplerini sınıflandırır.\nb) İklimin etkilerini yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB3.1. Empati',
    olcmeDegerlendirme: 'Harita yorumlama, akran değerlendirme',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Vatan sevgisi, çevre bilinci',
    okuryazarlikBecerileri: 'Harita okuryazarlığı',
    zenginlestirme: 'İklim bölgeleri karşılaştırma',
    okulTemelliPlanlama: 'Bölge iklim sunumu',
    sortOrder: 11,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 12,
    unite: 'DOĞAL SİSTEMLER VE SÜREÇLER',
    konu: 'Yer Şekillerinin Oluşumu',
    kazanimlar:
      'COĞ.9.3.4. Yer şekillerinin oluşum süreçlerini açıklayabilme\na) İç ve dış kuvvetleri belirler.\nb) Yer şekillerinin oluşumundaki etkilerini değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, DB2.2. Yaratıcı Düşünme',
    olcmeDegerlendirme: 'Öğretmen gözlemi, sözlü sunum',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Bilimsellik, merak',
    okuryazarlikBecerileri: 'Görsel okuma, metin okuma',
    zenginlestirme: 'Yer şekli modeli yapımı',
    okulTemelliPlanlama: 'Görsel materyal inceleme',
    sortOrder: 12,
  },
  // Hafta 13-18: DOĞAL SİSTEMLER devamı + BEŞERÎ SİSTEMLER
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 13,
    unite: 'DOĞAL SİSTEMLER VE SÜREÇLER',
    konu: 'Türkiye\'de Yer Şekilleri',
    kazanimlar: 'COĞ.9.3.5. Türkiye\'deki yer şekillerini analiz edebilme\na) Türkiye\'deki yer şekillerini sınıflandırır.\nb) Yer şekillerinin dağılışını yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Harita analizi, performans görevi',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Vatan sevgisi, bilimsellik',
    okuryazarlikBecerileri: 'Harita okuryazarlığı',
    zenginlestirme: 'Yer şekli sunumu',
    okulTemelliPlanlama: 'Atlas kullanımı',
    sortOrder: 13,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 14,
    unite: 'DOĞAL SİSTEMLER VE SÜREÇLER',
    konu: 'Su Kaynakları ve Önemi',
    kazanimlar: 'COĞ.9.3.6. Su kaynaklarını değerlendirebilme\na) Su kaynaklarının dağılışını açıklar.\nb) Su kullanımı ve çevre ilişkisini değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB3.1. Empati',
    olcmeDegerlendirme: 'Öz değerlendirme, sunum',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Çevre bilinci, su tasarrufu',
    okuryazarlikBecerileri: 'Veri okuma, grafik yorumlama',
    zenginlestirme: 'Su kaynağı araştırması',
    okulTemelliPlanlama: 'Su tüketimi projesi',
    sortOrder: 14,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 15,
    unite: 'DOĞAL SİSTEMLER VE SÜREÇLER',
    konu: 'Toprak ve Bitki Örtüsü',
    kazanimlar: 'COĞ.9.3.7. Toprak ve bitki örtüsünü analiz edebilme\na) Toprak türlerini sınıflandırır.\nb) Bitki örtüsü dağılışını yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, DB2.2. Yaratıcı Düşünme',
    olcmeDegerlendirme: 'Kavram haritası, gözlem formu',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Doğa sevgisi, sorumluluk',
    okuryazarlikBecerileri: 'Görsel okuma, harita okuryazarlığı',
    zenginlestirme: 'Bitki örtüsü haritası analizi',
    okulTemelliPlanlama: 'Okul bahçesi gözlemi',
    sortOrder: 15,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 16,
    unite: 'BEŞERÎ SİSTEMLER VE SÜREÇLER',
    konu: 'Nüfusun Tarihsel Değişimi',
    kazanimlar: 'COĞ.9.4.1. Nüfusun tarihsel değişimini çözümleyebilme\na) Nüfus verilerini yorumlar.\nb) Nüfus değişiminin sonuçlarını değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Grafik yorumlama, öğretmen gözlemi',
    sosyalDuygusal: 'SDB3.1. Empati',
    degerler: 'Dayanışma, insan hakları',
    okuryazarlikBecerileri: 'Veri okuryazarlığı, grafik okuma',
    zenginlestirme: 'Nüfus grafiği çizimi',
    okulTemelliPlanlama: 'İstatistik analizi',
    sortOrder: 16,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 17,
    unite: 'BEŞERÎ SİSTEMLER VE SÜREÇLER',
    konu: 'Nüfus Dağılışı ve Hareketleri',
    kazanimlar: 'COĞ.9.4.2. Nüfus dağılışını ve hareketlerini analiz edebilme\na) Nüfus dağılışını haritalardan çıkarır.\nb) Göç nedenleri ve sonuçlarını değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.2. İş Birliği',
    olcmeDegerlendirme: 'Harita yorumlama, akran değerlendirme',
    sosyalDuygusal: 'SDB3.1. Empati, SDB3.2. Değer Verme',
    degerler: 'Hoşgörü, dayanışma',
    okuryazarlikBecerileri: 'Harita okuryazarlığı',
    zenginlestirme: 'Göç haritası analizi',
    okulTemelliPlanlama: 'Sözlü tarih projesi',
    sortOrder: 17,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 18,
    unite: 'BEŞERÎ SİSTEMLER VE SÜREÇLER',
    konu: 'Demografik Dönüşüm ve Nüfus Piramitleri',
    kazanimlar: 'COĞ.9.4.3. Demografik dönüşümü açıklayabilme\na) Nüfus piramitlerini yorumlar.\nb) Ülkeler arası demografik farklılıkları karşılaştırır.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, DB2.2. Yaratıcı Düşünme',
    olcmeDegerlendirme: 'Performans görevi, sözlü sunum',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Bilimsellik, karşılaştırmalı düşünme',
    okuryazarlikBecerileri: 'Grafik okuma, veri yorumlama',
    zenginlestirme: 'Nüfus piramidi çizimi',
    okulTemelliPlanlama: 'Karşılaştırmalı analiz',
    sortOrder: 18,
  },
  // Hafta 19-24: BEŞERÎ SİSTEMLER devamı + EKONOMİK FAALİYETLER
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 19,
    unite: 'BEŞERÎ SİSTEMLER VE SÜREÇLER',
    konu: 'Nüfus Politikaları',
    kazanimlar: 'COĞ.9.4.4. Nüfus politikalarını değerlendirebilme\na) Nüfus politikalarının amaçlarını açıklar.\nb) Politikaların etkilerini yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB3.2. Değer Verme',
    olcmeDegerlendirme: 'Tartışma değerlendirme, öz değerlendirme',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Sorumluluk, insan hakları',
    okuryazarlikBecerileri: 'Metin okuma, argüman analizi',
    zenginlestirme: 'Politika karşılaştırma',
    okulTemelliPlanlama: 'Tartışma etkinliği',
    sortOrder: 19,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 20,
    unite: 'EKONOMİK FAALİYETLER VE ETKİLERİ',
    konu: 'Ekonomik Faaliyetlerin Sınıflandırılması',
    kazanimlar: 'COĞ.9.5.1. Ekonomik faaliyetleri sınıflandırabilme\na) Birincil, ikincil ve üçüncül sektörleri ayırt eder.\nb) Ekonomik faaliyetleri coğrafi faktörlerle ilişkilendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, DB2.1. Araştırma',
    olcmeDegerlendirme: 'Kavram haritası, sözlü sunum',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Üretkenlik, sorumluluk',
    okuryazarlikBecerileri: 'Metin okuma, sınıflandırma',
    zenginlestirme: 'Faaliyet türü örnekleri',
    okulTemelliPlanlama: 'Grup sınıflandırma',
    sortOrder: 20,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 21,
    unite: 'EKONOMİK FAALİYETLER VE ETKİLERİ',
    konu: 'Tarım ve Hayvancılık',
    kazanimlar: 'COĞ.9.5.2. Tarım faaliyetlerini analiz edebilme\na) Tarımın coğrafi dağılışını açıklar.\nb) Türkiye\'deki tarım bölgelerini yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Harita analizi, performans görevi',
    sosyalDuygusal: 'SDB3.1. Empati',
    degerler: 'Üretkenlik, doğa sevgisi',
    okuryazarlikBecerileri: 'Harita okuryazarlığı',
    zenginlestirme: 'Tarım bölgesi sunumu',
    okulTemelliPlanlama: 'Bölge haritası analizi',
    sortOrder: 21,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 22,
    unite: 'EKONOMİK FAALİYETLER VE ETKİLERİ',
    konu: 'Sanayi ve Enerji',
    kazanimlar: 'COĞ.9.5.3. Sanayi faaliyetlerini değerlendirebilme\na) Sanayinin dağılışını açıklar.\nb) Enerji kaynakları ve kullanımını yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.2. Yaratıcı Düşünme, SDB2.2. İş Birliği',
    olcmeDegerlendirme: 'Sunum, öğretmen gözlemi',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Çevre bilinci, enerji tasarrufu',
    okuryazarlikBecerileri: 'Grafik okuma, veri yorumlama',
    zenginlestirme: 'Enerji kaynağı araştırması',
    okulTemelliPlanlama: 'Sanayi haritası analizi',
    sortOrder: 22,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 23,
    unite: 'EKONOMİK FAALİYETLER VE ETKİLERİ',
    konu: 'Hizmet Sektörü ve Ulaşım',
    kazanimlar: 'COĞ.9.5.4. Hizmet sektörünü analiz edebilme\na) Hizmet sektörünün önemini açıklar.\nb) Ulaşım ağlarının mekânsal etkilerini değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Ulaşım haritası analizi, sunum',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Dayanışma, etkinlik',
    okuryazarlikBecerileri: 'Harita okuryazarlığı',
    zenginlestirme: 'Ulaşım ağı projesi',
    okulTemelliPlanlama: 'Bölgesel ulaşım analizi',
    sortOrder: 23,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 24,
    unite: null,
    konu: '2. DÖNEM SINAV HAFTASI',
    kazanimlar: null,
    dersSaati: 1,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: '2. dönem ara sınavı',
    sosyalDuygusal: 'SDB1.2. Kendini Düzenleme',
    degerler: 'Dürüstlük, sorumluluk',
    okuryazarlikBecerileri: 'Sınav okuryazarlığı',
    zenginlestirme: null,
    okulTemelliPlanlama: 'Sınav uygulaması',
    sortOrder: 24,
  },
  // Hafta 25-30: AFETLER VE SÜRDÜRÜLEBİLİR ÇEVRE
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 25,
    unite: 'AFETLER VE SÜRDÜRÜLEBİLİR ÇEVRE',
    konu: 'Tehlike, Risk ve Afet Kavramları',
    kazanimlar: 'COĞ.9.6.1. Tehlike ve afet kavramlarını ayırt edebilme\na) Tehlike, risk ve afet kavramlarını tanımlar.\nb) Afet türlerini sınıflandırır.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.1. Kendini Tanıma, DB2.1. Araştırma',
    olcmeDegerlendirme: 'Kavram haritası, öğretmen gözlemi',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Sorumluluk, dayanışma',
    okuryazarlikBecerileri: 'Metin okuma, sınıflandırma',
    zenginlestirme: 'Afet kavramı sunumu',
    okulTemelliPlanlama: 'Kavram ayrımı etkinliği',
    sortOrder: 25,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 26,
    unite: 'AFETLER VE SÜRDÜRÜLEBİLİR ÇEVRE',
    konu: 'Afet Türleri',
    kazanimlar: 'COĞ.9.6.2. Afet türlerini sınıflandırabilme\na) Doğal ve insan kaynaklı afetleri ayırt eder.\nb) Afetlerin mekânsal dağılışını yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB3.1. Empati',
    olcmeDegerlendirme: 'Harita analizi, performans görevi',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Dayanışma, çevre bilinci',
    okuryazarlikBecerileri: 'Harita okuryazarlığı',
    zenginlestirme: 'Afet haritası projesi',
    okulTemelliPlanlama: 'Afet türü sınıflandırma',
    sortOrder: 26,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 27,
    unite: 'AFETLER VE SÜRDÜRÜLEBİLİR ÇEVRE',
    konu: 'Bütüncül Afet Yönetimi',
    kazanimlar: 'COĞ.9.6.3. Afet yönetimini değerlendirebilme\na) Afet öncesi, sırası ve sonrası önlemleri açıklar.\nb) Sürdürülebilir çevre ilişkisini kurar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.2. Yaratıcı Düşünme, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Sunum, öz değerlendirme',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Sorumluluk, hazırlıklı olma',
    okuryazarlikBecerileri: 'Metin okuma, prosedür okuryazarlığı',
    zenginlestirme: 'Afet planı hazırlama',
    okulTemelliPlanlama: 'Okul afet tatbikatı',
    sortOrder: 27,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 28,
    unite: 'AFETLER VE SÜRDÜRÜLEBİLİR ÇEVRE',
    konu: 'Sürdürülebilirlik ve Çevre',
    kazanimlar: 'COĞ.9.6.4. Sürdürülebilir çevreyi analiz edebilme\na) Sürdürülebilirlik kavramını açıklar.\nb) Çevre sorunları ve çözümlerini değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB3.1. Empati',
    olcmeDegerlendirme: 'Tartışma, akran değerlendirme',
    sosyalDuygusal: 'SDB3.2. Değer Verme',
    degerler: 'Çevre bilinci, sürdürülebilirlik',
    okuryazarlikBecerileri: 'Çevre okuryazarlığı',
    zenginlestirme: 'Sürdürülebilirlik projesi',
    okulTemelliPlanlama: 'Çevre koruma etkinliği',
    sortOrder: 28,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 29,
    unite: 'AFETLER VE SÜRDÜRÜLEBİLİR ÇEVRE',
    konu: 'Türkiye\'de Afetler',
    kazanimlar: 'COĞ.9.6.5. Türkiye\'deki afet risklerini değerlendirebilme\na) Türkiye\'deki afet türlerini sıralar.\nb) Afet yönetimi uygulamalarını yorumlar.',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB2.1. Araştırma, SDB2.1. İletişim',
    olcmeDegerlendirme: 'Harita analizi, sunum',
    sosyalDuygusal: 'SDB3.1. Empati',
    degerler: 'Sorumluluk, vatan sevgisi',
    okuryazarlikBecerileri: 'Harita okuryazarlığı',
    zenginlestirme: 'Türkiye afet risk haritası',
    okulTemelliPlanlama: 'Bölgesel afet analizi',
    sortOrder: 29,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 30,
    unite: 'AFETLER VE SÜRDÜRÜLEBİLİR ÇEVRE',
    konu: 'İklim Değişikliği',
    kazanimlar: 'COĞ.9.6.6. İklim değişikliğini analiz edebilme\na) İklim değişikliğinin nedenlerini açıklar.\nb) Etkileri ve önlemleri değerlendirir.',
    dersSaati: 2,
    belirliGunHaftalar: '22 Nisan Dünya Günü',
    surecBilesenleri: 'DB2.1. Araştırma, SDB3.2. Değer Verme',
    olcmeDegerlendirme: 'Tartışma, öz değerlendirme',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Çevre bilinci, sorumluluk',
    okuryazarlikBecerileri: 'Veri okuma, grafik yorumlama',
    zenginlestirme: 'İklim değişikliği projesi',
    okulTemelliPlanlama: 'Dünya Günü etkinliği',
    sortOrder: 30,
  },
  // Hafta 31-36: Genel tekrar ve değerlendirme
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 31,
    unite: 'GENEL TEKRAR',
    konu: '1. ve 2. Ünite Tekrar',
    kazanimlar: 'COĞ.9.1-9.2 ünite kazanımlarının pekiştirilmesi',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: 'Tekrar testi, öğretmen gözlemi',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Çalışkanlık, düzen',
    okuryazarlikBecerileri: 'Kavram tekrarı',
    zenginlestirme: 'Kavram haritası özeti',
    okulTemelliPlanlama: 'Ünite tekrar oturumu',
    sortOrder: 31,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 32,
    unite: 'GENEL TEKRAR',
    konu: '3. ve 4. Ünite Tekrar',
    kazanimlar: 'COĞ.9.3-9.4 ünite kazanımlarının pekiştirilmesi',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: 'Tekrar testi, akran değerlendirme',
    sosyalDuygusal: 'SDB2.2. İş Birliği',
    degerler: 'Çalışkanlık, dayanışma',
    okuryazarlikBecerileri: 'Harita ve grafik tekrarı',
    zenginlestirme: 'Özet tablo hazırlama',
    okulTemelliPlanlama: 'Ünite tekrar oturumu',
    sortOrder: 32,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 33,
    unite: 'GENEL TEKRAR',
    konu: '5. ve 6. Ünite Tekrar',
    kazanimlar: 'COĞ.9.5-9.6 ünite kazanımlarının pekiştirilmesi',
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: 'Tekrar testi, öz değerlendirme',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Çalışkanlık, sorumluluk',
    okuryazarlikBecerileri: 'Kavram tekrarı',
    zenginlestirme: 'Ünite özet kartları',
    okulTemelliPlanlama: 'Ünite tekrar oturumu',
    sortOrder: 33,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 34,
    unite: null,
    konu: 'YIL SONU DEĞERLENDİRME HAZIRLIĞI',
    kazanimlar: null,
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: 'Deneme sınavı, öğretmen gözlemi',
    sosyalDuygusal: 'SDB1.2. Kendini Düzenleme',
    degerler: 'Sorumluluk, düzen',
    okuryazarlikBecerileri: 'Sınav stratejileri',
    zenginlestirme: 'Sorunlu konu tekrarı',
    okulTemelliPlanlama: 'Sınav hazırlık oturumu',
    sortOrder: 34,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 35,
    unite: null,
    konu: 'YIL SONU DEĞERLENDİRME',
    kazanimlar: null,
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: 'Yıl sonu sınavı',
    sosyalDuygusal: 'SDB1.2. Kendini Düzenleme',
    degerler: 'Dürüstlük, sorumluluk',
    okuryazarlikBecerileri: 'Sınav okuryazarlığı',
    zenginlestirme: null,
    okulTemelliPlanlama: 'Sınav uygulaması',
    sortOrder: 35,
  },
  {
    subjectCode: 'cografya',
    subjectLabel: 'Coğrafya',
    grade: 9,
    section: 'ders',
    academicYear: ACADEMIC_YEAR,
    weekOrder: 36,
    unite: null,
    konu: 'DERS YILI KAPANIŞI',
    kazanimlar: null,
    dersSaati: 2,
    belirliGunHaftalar: null,
    surecBilesenleri: 'DB1.2. Kendini Değerlendirme',
    olcmeDegerlendirme: 'Yıl sonu değerlendirme',
    sosyalDuygusal: 'SDB2.1. İletişim',
    degerler: 'Sorumluluk, tamamlanma',
    okuryazarlikBecerileri: 'Öz değerlendirme',
    zenginlestirme: 'Yaz tatili önerileri',
    okulTemelliPlanlama: 'Kapanış etkinliği',
    sortOrder: 36,
  },
];

async function main() {
  const app = await NestFactory.createApplicationContext(AppModule);
  try {
    const wcRepo = app.get<Repository<WorkCalendar>>(getRepositoryToken(WorkCalendar));
    const ypRepo = app.get<Repository<YillikPlanIcerik>>(getRepositoryToken(YillikPlanIcerik));

    // Mevcut veriyi silip yeniden ekle (güncel takvim ve plan için)
    const deletedWc = await wcRepo.delete({ academicYear: ACADEMIC_YEAR });
    console.log(`${deletedWc.affected ?? 0} çalışma takvimi kaydı silindi.`);

    for (const w of WORK_CALENDAR) {
      await wcRepo.save(wcRepo.create(w));
    }
    console.log(`${WORK_CALENDAR.length} hafta çalışma takvimi eklendi (${ACADEMIC_YEAR}).`);

    const deletedYp = await ypRepo.delete({
      subjectCode: 'cografya',
      grade: 9,
      academicYear: ACADEMIC_YEAR,
    });
    console.log(`${deletedYp.affected ?? 0} Coğrafya 9 plan kaydı silindi.`);

    for (const p of PLAN_ICERIK) {
      await ypRepo.save(ypRepo.create(p));
    }
    console.log(`${PLAN_ICERIK.length} hafta yıllık plan içeriği eklendi (Coğrafya 9, ${ACADEMIC_YEAR}).`);

    console.log('Deneme verisi hazır. Çalışma Takvimi ve Yıllık Plan İçerikleri sayfalarından görüntüleyebilirsiniz.');
  } catch (err) {
    console.error('Hata:', err instanceof Error ? err.message : err);
    process.exit(1);
  } finally {
    await app.close();
  }
}

main();
