/**
 * Öğretmen branşı önerileri (MEB ders kataloğu / ortaokul–lise + yaygın alanlar).
 * Sıra: Türkçe yerelleştirmeli alfabetik.
 */
const TEACHER_BRANCH_RAW: string[] = [
  'Almanca',
  'Arapça',
  'Beden Eğitimi ve Spor',
  'Bilgisayar Bilimi',
  'Bil. Tek. ve Yazılım',
  'Bilişim Teknolojileri ve Yazılım',
  'Birleştirilmiş Sınıf (1-2, 3-4)',
  'Biyoloji',
  'Coğrafya',
  'Din Kültürü ve Ahlak Bilgisi',
  'Drama',
  'Fen Bilimleri',
  'Felsefe',
  'Fizik',
  'Fransızca',
  'Görsel Sanatlar',
  'Hayat Bilgisi',
  'İngilizce',
  'İspanyolca',
  'Kimya',
  "Kur'an-ı Kerim",
  'Mantık',
  'Matematik',
  'Matematik Uygulamaları',
  'Müzik',
  'Okuma Becerileri',
  'Peygamberimizin Hayatı',
  'Psikoloji',
  'Psikolojik Danışmanlık ve Rehberlik',
  'Rehberlik',
  'Rusça',
  'Serbest Etkinlik',
  'Siyer',
  'Sosyal Bilgiler',
  'Sosyoloji',
  'Spor ve Fiziki Etkinlikler',
  'T.C. İnkılap Tarihi ve Atatürkçülük',
  'Tarih',
  'Teknoloji ve Tasarım',
  'Temel Dini Bilgiler',
  'Türk Dili ve Edebiyatı',
  'Türkçe',
  'Yapay Zeka ve Kodlama',
  'Yazarlık ve Yazma Becerileri',
  'Zeka Oyunları',
];

export const TEACHER_BRANCH_OPTIONS: readonly string[] = [...new Set(TEACHER_BRANCH_RAW)].sort((a, b) =>
  a.localeCompare(b, 'tr'),
);
