/** E-Okul sayfa kazıma seçicileri — deploy ile güncellenir. */
export const EOKUL_BRIDGE_DOM_RUNTIME = {
  exportPage: {
    mainFormSelectors: ['form#aspnetForm', 'form[name="aspnetForm"]', 'form#Form1'],
    mainFormLastChance: 'form',
    pageModeInputName: 'pageMode',
    classSelectSelectors: [
      '#Us_SinifSube1_ddlSinifSube',
      '#ddlSinifiSube',
      '#ddlSinifSube',
      'select[id*="Sinif" i]',
      'select[id*="Sube" i]',
    ],
    classSelectAppFormControl: '#app select.form-control',
    optionExcludeValue: '-1',
    listelePageModeValue: 'listele',
    listeleSubmitValue: 'Listele',
  },
  listeleUi: {
    clickableSelectorList: 'input[type="submit"],input[type="image"],button',
    submitButtonClass: 'btn',
    labelExactRegex: '^Listele$',
    labelLooseIncludes: 'listele',
    labelLooseMaxLen: 48,
  },
  tableScrape: {
    tableIds: ['#dgListem', '#tbPageDataTable', '#dgListe', '#grdListe'],
    minTdCount: 5,
    colSinif: 1,
    colTc: 2,
    colOgrNo: 3,
    colAdSoyad: 4,
    skipRowSelectors: ['.GridHeader', '.GridFooter'],
    skipRowTags: ['th'],
  },
  gunlukDevamsizlik: {
    listeleDateFieldName: 'Us_tarih1$txtTarihGiris',
    listeleDateFieldNameIok: 'txtTarih',
    gridTableId: '#dgListem',
    gridTableIds: {
      ortaOgretim: '#dgListem',
      ilkOgretim: '#tbPageDataTable',
      okulOncesi: '#tbPageDataTable',
    },
    checkboxColIndex: { tamGun: 5, yarimGun: 6, gec: 7 },
    checkboxNamePrefix: {
      tamGun: 'chkTamGun_',
      yarimGunSabah: 'chkYarimGunSabah_',
      yarimGunOglen: 'chkYarimGunOglen_',
      nobet: 'chkNobet_',
      gec: 'chkGec_',
    },
    dateInputSelectors: [
      '#Us_tarih1_txtTarihGiris',
      '#app input[type="date"].form-control',
      'input[name*="Tarih" i]',
    ],
  },
  okulAltTur: {
    oklSelectSelectors: [
      '#ddlOkulTuru',
      '#ddlOkulAltTuru',
      'select[id*="OkulAltTur" i]',
      'select[id*="OkulTuru" i]',
      'select[name*="OkulAltTur" i]',
    ],
    defaultOklMenuPageStem: 'OOK01001',
  },
  postback: {
    okulAltTurNeedle: 'ddlOkul|OkulAltTur|OkulTuru',
    okulAltTurChunk: 14000,
    eventTargetPatterns: [
      "WebForm_PostBackOptions\\([^,]*,\\s*['\"]([^'\"]+)['\"]",
      "__doPostBack\\s*\\(\\s*['\"]([^'\"]+)['\"]",
    ],
  },
  ozur02012: {
    tableId: '#tblOzursuzDevamsizlik',
    tableIds: ['#dgListe', 'table#Table6.frmDis', 'table.frmList', '#tblOzursuzDevamsizlik'],
    minTdOzursuz: 5,
    colSira: 2,
    colTarih: 3,
    colTur: 4,
    headerSiraLabel: 'Sıra No',
  },
  ozur02013: {
    pageModeYeni: 'yeniKayit',
    pageModeKaydet: 'kaydet_devam',
    hiddenKaydetValue: 'Kaydet',
    aciklamaMaxLen: 29,
    yarimNeedle: 'yarım|yarim',
    txtSureHalf: '0,5',
    txtSureFull: '1',
  },
};
