-- BİLSEM Coğrafya PÜY — 2024-2025 örnek yıllık plan (PDF ile uyumlu kazanım satırları)
-- Çalıştır (UTF-8 zorunlu; aksi halde CO?.P?Y, t?r gibi bozulur):
--   cd backend && node tools/run-sql-utf8.cjs migrations/seed-bilsem-cografya-puy-outcomes.sql
-- Docker: dosyayı UTF-8 cp edip: docker exec -e PGCLIENTENCODING=UTF8 ogretmenpro-db psql -U postgres -d ogretmenpro -f /tmp/s.sql

-- Aynı ders+yıl için eski şablonu kaldır (PDF seed tekrar çalışsın)
DELETE FROM bilsem_outcome_item WHERE bilsem_outcome_set_id IN (
  SELECT id FROM bilsem_outcome_set WHERE subject_code = 'bilsem_cografya' AND academic_year = '2024-2025'
);
DELETE FROM bilsem_outcome_set WHERE subject_code = 'bilsem_cografya' AND academic_year = '2024-2025';

WITH ins AS (
  INSERT INTO bilsem_outcome_set (id, yetenek_alani, yetenek_label, grup_adi, grade, academic_year, subject_code, subject_label, created_at, updated_at)
  VALUES (
    gen_random_uuid(),
    'GENEL_YETENEK',
    'Coğrafya',
    'Cografya PUY 2024-2025 PDF',
    NULL,
    '2024-2025',
    'bilsem_cografya',
    'Coğrafya',
    NOW(),
    NOW()
  )
  RETURNING id
)
INSERT INTO bilsem_outcome_item (
  id, bilsem_outcome_set_id, week_order, unite, code, description, sort_order, ders_saati,
  konu, surec_bilesenleri, olcme_degerlendirme, created_at, updated_at
)
SELECT gen_random_uuid(), ins.id, x.wo, x.u, x.c, x.d, x.so, 2, x.k, x.s, 'Kontrol listesi, ürün değerlendirmesi', NOW(), NOW()
FROM ins
CROSS JOIN (
  VALUES
  (1, 'Bilim ve Bilim Felsefesi', 'COĞ.PÜY.1.1', 'Bilgi türlerini ve kullanımlarını sorgulayabilme.', 0,
   'Bilgi türleri ve kullanımı',
   'Bilgi türlerini tanımlama; soru sorma; bilgi toplama; doğruluğu değerlendirme; çıkarım yapma.'),
  (2, 'Bilim ve Bilim Felsefesi', 'COĞ.PÜY.1.2–1.3', 'Toplumun farklı katmanlarında bilimin üretilmesini tahmin ve tartışabilme.', 1,
   'Toplumun farklı katmanlarında bilim',
   'Gözlem/deneyim ilişkilendirme; çıkarım ve yargı; mantıksal temellendirme ve tartışma.'),
  (3, 'Bilim ve Bilim Felsefesi', 'COĞ.PÜY.1.4', 'Bilimin gelişimi açısından bilimsel paradigmaları sınıflandırabilme.', 2,
   'Bilimsel paradigmalar',
   'Nitelikleri belirleme; ayrıştırma; gruplandırma; etiketleme.'),
  (4, 'Bilim ve Etik', 'COĞ.PÜY.2.1–2.2', 'Bilimsel araştırmalarda etik kavramını sorgulama; araştırma ve yayın ahlakında eleştirel düşünme.', 3,
   'Bilimsel araştırma ve yayın ahlakı (etik eğitimi)',
   'Etik kavramı; 5N1K ile soru; bilgi toplama ve değerlendirme; akıl yürütme ve yansıtma.'),
  (5, 'Bilim ve Etik', 'COĞ.PÜY.2.3', 'Etik ihlallere karşı alınan önlemleri sorgulayabilme.', 4,
   'Etik ihlallere karşı alınan önlemler',
   'Tanımlama; soru sorma; bilgi toplama; doğruluk değerlendirme; çıkarım.'),
  (6, 'Proje Tabanlı Öğrenme', 'COĞ.PÜY.3.1', 'Proje tabanlı öğrenmenin bileşenlerini çözümleyebilme.', 5,
   'Proje tabanlı öğrenmenin bileşenleri',
   'Bileşenleri belirleme; bileşenler arası ilişkiyi belirleme.'),
  (7, 'Proje Tabanlı Öğrenme', 'COĞ.PÜY.3.2', 'Proje tabanlı öğrenmenin faydalarını sorgulayabilme.', 6,
   'Proje tabanlı öğrenmenin faydaları',
   'Tanımlama; soru sorma; bilgi toplama; doğruluk değerlendirme; çıkarım.'),
  (8, 'Proje Tabanlı Öğrenme', 'COĞ.PÜY.3.3–3.4', 'PÖ''nün girişimciliğe etkisini yapılandırma ve yorumlama.', 7,
   'Proje tabanlı öğrenmede girişimcilik',
   'Nedensel ilişkiler; bütünleştirme; inceleme ve dönüştürme; kendi cümleleriyle aktarma.'),
  (9, 'Proje Tabanlı Öğrenme', 'COĞ.PÜY.3.5', 'PÖ bağlamında SMK ve FSEK''teki hakların yerini yapılandırabilme.', 8,
   'Sınai Mülkiyet ve Fikir-Sanat Eserleri Kanunu',
   'Hakların yeri ve önemini inceleme; bilgileri bütünleştirme.'),
  (10, 'Proje Türleri / Araştırma projeleri', 'COĞ.PÜY.4.1', 'Araştırma projelerini sınıflandırabilme.', 9,
   'Araştırma projelerine ilişkin ölçütler',
   'Ölçüt belirleme; nesne/olgu ayrıştırma; tasnif; etiketleme.'),
  (11, 'Bilimsel araştırma projeleri ve özellikleri', 'COĞ.PÜY.4.2', 'Bilimsel araştırma projelerinin özelliklerini karşılaştırabilme.', 10,
   'Bilimsel araştırma projelerinin özellikleri',
   'Özellikleri belirleme; benzerlik ve farkları listeleme.'),
  (12, 'Diğer proje türleri', 'COĞ.PÜY.4.3', 'Bilimsel araştırma dışı proje türlerinin özelliklerini karşılaştırabilme.', 11,
   'Diğer proje türleri ve özellikleri',
   'Tür ve özellikleri belirleme; benzerlik ve farkları listeleme.'),
  (13, 'Araştırma projeleri', 'COĞ.PÜY.4.4', 'Bilimsel araştırma projeleri ile diğer proje çeşitlerini karşılaştırabilme.', 12,
   'Proje çeşitlerinin karşılaştırılması',
   'Belirleme; benzerlik ve farkları listeleme.'),
  (14, 'Diğer proje türleri ve özellikleri', 'COĞ.PÜY.4.5–4.6', 'Bilimsel ve diğer proje özelliklerini sentezleyebilme.', 13,
   'Özelliklerin sentezi',
   'İlişki kurma; özgün bütün oluşturma.'),
  (15, 'Öğrencilerin coğrafi ilgilerini keşfetmeleri', 'COĞ.PÜY.5.1', 'Geçmişte yaşanmış coğrafi sorunları çözümleyebilme.', 14,
   'Geçmişte yaşanmış coğrafi sorunların analizi',
   'Bileşenleri ve bileşenler arası ilişkileri belirleme.'),
  (16, 'Öğrencilerin coğrafi ilgilerini keşfetmeleri', 'COĞ.PÜY.5.2', 'Günümüzde yaşanan coğrafi sorunları çözümleyebilme.', 15,
   'Günümüzde yaşanan coğrafi sorunların analizi',
   'Bileşenleri ve ilişkileri belirleme.'),
  (17, 'Öğrencilerin coğrafi ilgilerini keşfetmeleri', 'COĞ.PÜY.5.3–5.4', 'Gelecekte yaşanabilecek coğrafi sorunları veriye dayalı tahmin ve tartışabilme.', 16,
   'Gelecekte yaşanabilecek coğrafi sorunlar',
   'Veri toplama; projeksiyon; yargı; mantıksal temellendirme ve tartışma.'),
  (18, 'Proje konusu belirlemede özgünlük', 'COĞ.PÜY.6.1–6.2', 'Literatürden bilgi toplayıp özetteyebilme (konu tespiti).', 17,
   'Literatür tarama ve konu seçimi',
   'Araç belirleme; kaynak bulma; doğrulama; kayıt; çözümleme ve özetleme.'),
  (19, 'Proje konusu belirlemede özgünlük', 'COĞ.PÜY.6.3–6.4', 'Özgün proje konusuna karar verme ve özgünlüğü değerlendirme.', 18,
   'Proje konusunun özgünlüğünü test etme',
   'Amaç; bilgi; alternatifler; mantıksal denetleme; ölçüt ve ölçme.'),
  (20, 'Proje konusu belirlemede özgünlük', 'COĞ.PÜY.6.5', 'Proje paydaşlarını belirlerken sorgulama yapabilme.', 19,
   'Proje paydaşlarının belirlenmesi',
   'Tanımlama; soru; bilgi toplama; doğruluk; çıkarım.'),
  (21, 'Proje konusu belirlemede özgünlük', 'COĞ.PÜY.6.6', 'İhtiyaç durumuna göre ortak ve/veya faydalanıcıları belirlemede sorgulama.', 20,
   'Ortaklar ve faydalanıcılar',
   'Tanımlama; soru; bilgi toplama; doğruluk; çıkarım.'),
  (22, 'Proje planı ve iş takvimi', 'COĞ.PÜY.7.1–7.2', 'İş paketleri/zaman çizelgelerinde iş birliği; gerektiğinde bütçe bileşenlerine karar verme.', 21,
   'Proje planı, iş takvimi ve bütçe',
   'Kronolojik sıralama; bütçe amaç ve alternatifleri; yansıtma.'),
  (23, 'Projenin hazırlanması, geliştirilmesi ve sonuçlandırılması', 'COĞ.PÜY.8.1–8.2', 'Giriş bölümü için literatürden bilgi; hipotez yapılandırma.', 22,
   'Projenin giriş bölümünün yazılması',
   'Kaynak bulma; analiz ve alt başlıklar; problem ve hipotez.'),
  (24, 'Projede kullanılacak bilimsel araştırma deseni', 'COĞ.PÜY.8.3–8.5', 'Bilimsel araştırma yöntemlerinin önemini çözümleme; nicel ve nitel araştırmaları sorgulama.', 23,
   'Bilimsel araştırma yöntemleri (nicel–nitel)',
   'Parçalar ve ilişkiler; sorgulama süreçleri.'),
  (25, 'Projede kullanılacak bilimsel araştırma deseni', 'COĞ.PÜY.8.7–8.8', 'Karma araştırmaları sorgulama; desene karar verme.', 24,
   'Karma araştırma ve desen seçimi',
   'Bilgi toplama; alternatifler; mantıksal denetleme; seçim ve yansıtma.'),
  (26, 'Projede kullanılacak bilimsel araştırma deseni', 'COĞ.PÜY.8.9', 'Evren, örneklem veya çalışma grubuna karar verebilme.', 25,
   'Evren, örneklem veya çalışma grubu',
   'Amaç; bilgi; alternatifler; denetim; seçim; yansıtma.'),
  (27, 'Projede veri toplama ve analizi', 'COĞ.PÜY.8.10–8.11', 'Veri toplama araçlarına karar verme ve veri toplama.', 26,
   'Veri toplama araçları ve uygulama',
   'Amaç; bilgi; seçenekler; toplama ve kayıt.'),
  (28, 'Projede veri toplama ve analizi', 'COĞ.PÜY.8.12–8.14', 'Analiz araçlarını sorgulama; veriyi çözümleme ve sınıflandırma.', 27,
   'Veri analizi ve sınıflandırma',
   'SPSS/Nvivo vb. sorgulama; parça ve ilişkiler; değişken ve tasnif.'),
  (29, 'Projedeki bulgu ve yorumlar', 'COĞ.PÜY.8.15–8.16', 'Bulguları yapılandırma; tablo, grafik ve diyagram hazırlama.', 28,
   'Bulguların yapılandırılması ve görselleştirilmesi',
   'İlişkiler; görselleştirme adımları.'),
  (30, 'Projedeki bulgu ve yorumlar', 'COĞ.PÜY.8.17', 'Bulguları yorumlayabilme.', 29,
   'Bulguların yorumlanması',
   'İnceleme; dönüştürme; nesnel yeniden ifade.'),
  (31, 'Projenin tartışma, sonuç ve öneriler bölümü', 'COĞ.PÜY.8.18–8.19', 'Sonuçları diğer çalışmalarla karşılaştırma; tartışmaları değerlendirme.', 30,
   'Karşılaştırma ve tartışma değerlendirmesi',
   'Ölçüt; ölçme; karşılaştırma ve yargı.'),
  (32, 'Projenin tartışma, sonuç ve öneriler bölümü', 'COĞ.PÜY.8.20', 'Paydaşlara yönelik önerileri yapılandırabilme.', 31,
   'Önerilerin yapılandırılması',
   'İlişki kurarak öneri ve bütünleştirme.'),
  (33, 'Proje için etkili sunum teknikleri', 'COĞ.PÜY.9.1', 'Sunum için teknolojik araçlara karar verebilme.', 32,
   'Görsel materyaller ve sunum araçları',
   'Amaç; bilgi; alternatifler; seçim; yansıtma.'),
  (34, 'Proje için etkili sunum teknikleri', 'COĞ.PÜY.9.2', 'Sözlü sunumu eyleme dönüştürebilme.', 33,
   'Sözlü sunum hazırlama',
   'Planlama; uygulama; değerlendirme.'),
  (35, 'Proje çıktılarının ürüne dönüştürülmesi', 'COĞ.PÜY.10.1–10.3', 'Bilimsel platformda eyleme dönüştürme; yaygınlaştırma araçları; yayın.', 34,
   'Yaygınlaştırma ve yayın',
   'Plan; uygulama; değerlendirme; yayın oluşturma ve tanıtma.'),
  (36, 'Proje çıktılarının ürüne dönüştürülmesi', 'COĞ.PÜY.11.1', 'Proje çıktılarını uygun eserle sonuçlandırabilme.', 35,
   'Çıktıların ürüne dönüştürülmesi',
   'Eser oluşturma; tanıtma; değerlendirme.'),
  (37, 'Proje çıktılarının ürüne dönüştürülmesi', 'COĞ.PÜY.11.2–11.3', 'Eserleri yaygınlaştıracak araçlara karar verme ve bilimsel platformda eyleme dönüştürme (Sınai Mülkiyet).', 36,
   'Sınai Mülkiyet Kanunu kapsamında koruma',
   'Araç seçimi; plan; uygulama; değerlendirme.')
) AS x(wo, u, c, d, so, k, s);
