/** @type {string} */
var UZA_MSG_GATE_RUN = 'UZA_GATE_RUN';
var UZA_MSG_GATE_STATUS = 'UZA_GATE_STATUS';
var UZA_MSG_GATE_VERSION = 'UZA_GATE_VERSION';
var UZA_MSG_GATE_FEATURE = 'UZA_GATE_FEATURE';
var UZA_MSG_GATE_SCHOOL_ACCESS = 'UZA_GATE_SCHOOL_ACCESS';
var UZA_MSG_GATE_VERIFY_CODE = 'UZA_GATE_VERIFY_CODE';
var UZA_MSG_GATE_DIAGNOSTIC = 'UZA_GATE_DIAGNOSTIC';
var UZA_BRIDGE_CODE_VERIFIED_KEY = 'uzaBridgeCodeVerified';
var UZA_MSG_GET_BOOTSTRAP = 'UZA_GET_BOOTSTRAP';
var UZA_MSG_GET_EXTENSION_UI = 'UZA_GET_EXTENSION_UI';
var UZA_MSG_KELEBEK_LIST = 'UZA_KELEBEK_LIST';
var UZA_MSG_KELEBEK_EXPORT = 'UZA_KELEBEK_EXPORT';
var UZA_MSG_DEVAMSIZLIK_EXPORT = 'UZA_DEVAMSIZLIK_EXPORT';
var UZA_MSG_MEKTUP_EXPORT = 'UZA_MEKTUP_EXPORT';
var UZA_MSG_TOPLAM_EXPORT = 'UZA_TOPLAM_EXPORT';
var UZA_MSG_GET_MEKTUP_PREFILL = 'UZA_GET_MEKTUP_PREFILL';
var UZA_MEKTUP_PREFILL_KEY = 'uzaMektupPrefill';
var UZA_MSG_REHBER_EXPORT = 'UZA_REHBER_EXPORT';
var UZA_MSG_IZIN_EXPORT = 'UZA_IZIN_EXPORT';
var UZA_MSG_DD_LIST_STUDIOS = 'UZA_DD_LIST_STUDIOS';
var UZA_MSG_DD_EOKUL_PREVIEW = 'UZA_DD_EOKUL_PREVIEW';
var UZA_MSG_DD_EOKUL_IMPORT = 'UZA_DD_EOKUL_IMPORT';
var UZA_MSG_DD_LIST_PROGRAMS = 'UZA_DD_LIST_PROGRAMS';
var UZA_MSG_DD_EOKUL_EXPORT = 'UZA_DD_EOKUL_EXPORT';
var UZA_MSG_DEVAMSIZLIK_CAMPAIGNS = 'UZA_DEVAMSIZLIK_CAMPAIGNS';
var UZA_MSG_DEVAMSIZLIK_WRITE_PAYLOAD = 'UZA_DEVAMSIZLIK_WRITE_PAYLOAD';
var UZA_MSG_DEVAMSIZLIK_WRITE = 'UZA_DEVAMSIZLIK_WRITE';
var UZA_MSG_TOPLU_OZURSUZ_WRITE = 'UZA_TOPLU_OZURSUZ_WRITE';
var UZA_MSG_TOPLU_OZURLU_WRITE = 'UZA_TOPLU_OZURLU_WRITE';
var UZA_MSG_SET_KURUM = 'UZA_SET_KURUM';
var UZA_MSG_GET_KURUM = 'UZA_GET_KURUM';
var UZA_MSG_ORTA_OKUL_TUR_FETCH = 'UZA_ORTA_OKUL_TUR_FETCH';
var UZA_MSG_ORTA_OKUL_TUR_SET = 'UZA_ORTA_OKUL_TUR_SET';
var UZA_MSG_GET_ORTA_OKUL_TUR = 'UZA_GET_ORTA_OKUL_TUR';
var UZA_MSG_OZURSUZ_LISTE = 'UZA_OZURSUZ_LISTE';
var UZA_MSG_OZURSUZ_AKTAR = 'UZA_OZURSUZ_AKTAR';
var UZA_MSG_VELI_IZIN_PDF = 'UZA_VELI_IZIN_PDF';
var UZA_MSG_OGRENCI_DOSYA_EXPORT = 'UZA_OGRENCI_DOSYA_EXPORT';
var UZA_MSG_VELI_PUSH = 'UZA_VELI_PUSH';
var UZA_MSG_FAALIYET_WRITE = 'UZA_FAALIYET_WRITE';
var UZA_MSG_OPEN_GUNLUK_YAZ = 'UZA_OPEN_GUNLUK_YAZ';
var UZA_MSG_OPEN_APP = 'UZA_OPEN_APP';
var UZA_MSG_MEB_AJANDA_VERIFY = 'UZA_MEB_AJANDA_VERIFY';
var UZA_MSG_DD_EOKUL_UPLOAD_TO_MEB = 'UZA_DD_EOKUL_UPLOAD_TO_MEB';
var UZA_MSG_BORDRO_PARSE = 'UZA_BORDRO_PARSE';
var UZA_MSG_BORDRO_CAMPAIGN = 'UZA_BORDRO_CAMPAIGN';
var UZA_MSG_BORDRO_SCRAPE_PARSE = 'UZA_BORDRO_SCRAPE_PARSE';
var UZA_MSG_BORDRO_SCRAPE_CAMPAIGN = 'UZA_BORDRO_SCRAPE_CAMPAIGN';
var UZA_MSG_BORDRO_OPEN_TAB = 'UZA_BORDRO_OPEN_TAB';
var UZA_MSG_BORDRO_LAST_EXCEL_PARSE = 'UZA_BORDRO_LAST_EXCEL_PARSE';
var UZA_MSG_BORDRO_CAPTURE_URL = 'UZA_BORDRO_CAPTURE_URL';
var UZA_MSG_BORDRO_SNAPSHOT_MEBBIS = 'UZA_BORDRO_SNAPSHOT_MEBBIS';
var UZA_MSG_BORDRO_SNAPSHOT_KBS = 'UZA_BORDRO_SNAPSHOT_KBS';
var UZA_MSG_BORDRO_COMPARE = 'UZA_BORDRO_COMPARE';
var UZA_MSG_BORDRO_TC_AUDIT = 'UZA_BORDRO_TC_AUDIT';
var UZA_MSG_BORDRO_OPEN_MEBBIS_REPORT = 'UZA_BORDRO_OPEN_MEBBIS_REPORT';
var UZA_MSG_BORDRO_MEBBIS_VIEW_REPORT = 'UZA_BORDRO_MEBBIS_VIEW_REPORT';
var UZA_MSG_BORDRO_SCRAPE_DIAG = 'UZA_BORDRO_SCRAPE_DIAG';
var UZA_MSG_BORDRO_KBS_CLICK_EXPORT = 'UZA_BORDRO_KBS_CLICK_EXPORT';
/** @deprecated */ var UZA_MSG_BORDRO_MAAS_CLICK_EXPORT = UZA_MSG_BORDRO_KBS_CLICK_EXPORT;
var UZA_MSG_MEBBIS_OTURUM_SET = 'UZA_MEBBIS_OTURUM_SET';
var UZA_MEBBIS_OTURUM_ENABLED_KEY = 'uzaMebbisPingEnabled';
var UZA_MEBBIS_OTURUM_ALARM = 'uzaMebbisOturumPing';
var UZA_MSG_OTURUM_SET = 'UZA_OTURUM_SET';
var UZA_OTURUM_ALARM = 'uzaEokulOturumPing';
var UZA_OTURUM_ENABLED_KEY = 'uzaOturumPingEnabled';
var UZA_MSG_KBS_OTURUM_SET = 'UZA_KBS_OTURUM_SET';
var UZA_KBS_OTURUM_ENABLED_KEY = 'uzaKbsPingEnabled';
var UZA_KBS_OTURUM_ALARM = 'uzaKbsOturumPing';
var UZA_SESSION_GATE_KEY = 'uzaGatePayload';
var UZA_MSG_FLOAT_STORAGE_GET = 'UZA_FLOAT_STORAGE_GET';
var UZA_MSG_FLOAT_STORAGE_SET = 'UZA_FLOAT_STORAGE_SET';
var UZA_MSG_FLOAT_SESSION_GET = 'UZA_FLOAT_SESSION_GET';
var UZA_FLOAT_FAB_POS_KEY = 'uzaFloatFabPos';

/** Teknik hata metinlerini kullanıcıya anlaşılır Türkçe’ye çevirir. */
function uzaHumanError(raw) {
  var s = String(raw || '').trim();
  if (!s) return 'İşlem tamamlanamadı.';
  if (/is not defined/i.test(s)) {
    return 'Eklenti sürümü eski veya yeniden yüklenmeli: chrome://extensions → Uzaedu Okul Köprüsü → Yenile, sonra panel sekmesinde F5.';
  }
  if (/panel sekmesi|Panele giriş|panel sekmesinde/i.test(s)) return s;
  if (/ReferenceError|UZA_[A-Z0-9_]+/i.test(s)) {
    return 'Eklenti yapılandırma hatası. Köprüyü yeniden yükleyip (0.6+) tekrar deneyin.';
  }
  if (/Could not establish connection|Receiving end does not exist/i.test(s)) {
    return 'Sayfa henüz hazır değil. İlgili MEB sekmesini yenileyip tekrar deneyin.';
  }
  if (/Failed to fetch|NetworkError/i.test(s)) {
    return 'Sunucuya ulaşılamadı. Backend ve internet bağlantınızı kontrol edin.';
  }
  return s;
}
