/**
 * Akademik takvim şablonu sayfasında sürükle-bırak için kullanılacak palet öğeleri.
 * Takvimio/MEB belirli gün ve haftalar + öğretmen işleri listesi.
 */

export const BELIRLI_PALETTE: string[] = [
  'Uluslararası Temiz Hava Günü',
  'İlköğretim Haftası',
  'Dünyayı Temizlik Günü (7 Eylül)',
  'Mevlid-i Nebî Haftası',
  'Gaziler Günü',
  'Türk Dil Bayramı',
  'Disleksi Haftası',
  'Dünya Disleksi Günü',
  'Hayvanları Koruma Günü',
  'Ahilik Kültürü Haftası',
  'Dünya Afet Azaltma Günü',
  'Birleşmiş Milletler Günü',
  'Cumhuriyet Bayramı',
  'Kızılay Haftası',
  'Organ Bağışı ve Nakli Haftası',
  'Lösemili Çocuklar Haftası',
  'Atatürk Haftası',
  'Afet Eğitimi Hazırlık Günü',
  'Dünya Diyabet Günü',
  'UNESCO Kuruluş Günü',
  'Dünya Felsefe Günü',
  'Dünya Çocuk Hakları Günü',
  'Ağız ve Diş Sağlığı Haftası',
  'Öğretmenler Günü',
  'Dünya Engelliler Günü',
  'Dünya Madenciler Günü',
  'Türk Kadınına Seçme ve Seçilme Hakkının Verilişi',
  'Mevlana Haftası',
  'İnsan Hakları ve Demokrasi Haftası',
  'Tutum, Yatırım ve Türk Malları Haftası',
  "Mehmet Akif Ersoy'u Anma Haftası",
  'Yılbaşı',
  'Verem Eğitimi ve Propaganda Haftası',
  'Enerji Tasarrufu Haftası',
  'Çalışan Gazeteciler Günü',
  'Dünya Kanser Günü',
  'Güvenli İnternet Günü',
  'Sivil Savunma Günü',
  'Vergi Haftası',
  'Yeşilay Haftası',
  'Girişimcilik Haftası',
  'Dünya Kadınlar Günü',
  'Bilim ve Teknoloji Haftası',
  "İstiklâl Marşı'nın Kabulü ve Mehmet Akif Ersoy'u Anma Günü",
  "Çanakkale Zaferi ve Şehitleri Anma Günü",
  'Tüketiciyi Koruma Haftası',
  'Türk Dünyası ve Toplulukları Haftası',
  'Nevruz Bayramı',
  'Orman Haftası',
  'Dünya Meteoroloji Günü',
  'Dünya Tiyatrolar Günü',
  'Kütüphaneler Haftası',
  'Kanser Haftası',
  'Dünya Otizm Farkındalık Günü',
  'Dünya Sağlık Günü',
  'Kişisel Verileri Koruma Günü',
  'Turizm Haftası',
  'Dünya Fikrî Mülkiyet Günü',
  'Ulusal Egemenlik ve Çocuk Bayramı',
  "Kût'ül Amâre Zaferi",
  'Emek ve Dayanışma Günü',
  'Bilişim Haftası',
  'Trafik ve İlkyardım Haftası',
  'İş Sağlığı ve Güvenliği Haftası',
  'Karayolu Trafik Güvenliği Günü',
  'Engelliler Haftası',
  'Vakıflar Haftası',
  'Anneler Günü',
  'Aile Günü',
  "Müzeler Haftası",
  "Atatürk'ü Anma ve Gençlik ve Spor Bayramı",
  "Etik Günü",
  "İstanbul'un Fethi",
  'Hayat Boyu Öğrenme Haftası',
  'Dünya Çevre Günü',
  'Çevre ve İklim Değişikliği Haftası',
  'Babalar Günü',
  'Okul Öncesi Eğitim Haftası',
  'Oyun ve Oyuncak Haftası',
  'Meslek Eğitimi ve Teknoloji Haftası',
  'Çıraklık ve İşletmelerde Meslek Eğitimi Haftası',
  'Kaynaştırma ve Özel Eğitim Haftası',
  'Halk Eğitimi ve Kurs Haftası',
  'BILSEM ve Özel Yetenek Etkinlik Haftası',
  'İmam Hatip Okulları Etkinlik ve Değerler Haftası',
  'Okuma Kültürü ve Kitap Haftası',
  'Dünya Okul Öncesi Eğitim Günü',
  'Güvenli Okul ve Farkındalık Haftası',
  'Rehberlik ve Kariyer Haftası',
  'Meslek Tanıtım ve İşyeri Gezisi Haftası',
];

export const OGRETMEN_PALETTE: Array<{ title: string; path: string }> = [
  { title: 'Öğretmenler Kurulu', path: '/duty' },
  { title: 'Zümre Tutanakları', path: '/evrak' },
  { title: 'Yıllık Planlar', path: '/evrak' },
  { title: 'BEP Programı', path: '/evrak' },
  { title: 'Kulüp Planları', path: '/evrak' },
  { title: 'Şeflik Planlar', path: '/evrak' },
  { title: 'Kazanım Ara', path: '/evrak' },
  { title: 'Öğretmen Ağı', path: '/profile' },
  { title: 'Günlük Planlar', path: '/evrak' },
  { title: 'Kulüp Raporu', path: '/evrak' },
  { title: 'Şeflik Raporu', path: '/evrak' },
  { title: 'Sınav Hazırla', path: '/evrak' },
  { title: 'Soru Üret', path: '/evrak' },
  { title: 'Sınav Analizleri', path: '/evrak' },
  { title: 'Performans Değerlendir', path: '/evrak' },
  { title: 'Veli Toplantıları', path: '/evrak' },
  { title: 'Proje Asistanı', path: '/evrak' },
  { title: 'İdareye Teslim Evraklar', path: '/evrak' },
  { title: 'Oyun Temelli Öğrenme', path: '/evrak' },
  { title: 'Gelişim Takibi', path: '/evrak' },
  { title: 'LGS Hazırlık ve Rehberlik', path: '/evrak' },
  { title: 'YKS Hazırlık ve Rehberlik', path: '/evrak' },
  { title: 'TYT-AYT Çalışmaları', path: '/evrak' },
  { title: 'Staj ve İşyeri Eğitimi', path: '/evrak' },
  { title: 'Mesleki Yeterlilik ve MYK', path: '/evrak' },
  { title: 'Özel Eğitim BEP ve Raporlar', path: '/evrak' },
  { title: 'Halk Eğitimi Kurs Planları', path: '/evrak' },
  { title: 'BILSEM Özel Gelişim Programı', path: '/evrak' },
  { title: 'İHL Pedagojik ve Değerler Etkinlikleri', path: '/evrak' },
  { title: 'Okuma Yazma ve İlk Okuma', path: '/evrak' },
  { title: 'Rehberlik ve Sosyal Beceri', path: '/evrak' },
  { title: 'Tema Etkinliği ve Örnek', path: '/evrak' },
  { title: 'Sınıf İçi Oyun ve Drama', path: '/evrak' },
  { title: 'Meslek Atölyesi Uygulaması', path: '/evrak' },
  { title: 'Alan Seçimi ve Yönlendirme', path: '/evrak' },
  { title: 'Kurum Staj Değerlendirme', path: '/evrak' },
  { title: 'Kültür ve Sanat Atölyesi', path: '/evrak' },
  { title: 'Okuma Kültürü ve Kitap', path: '/evrak' },
];
