/**
 * Akademik takvim şablonu sayfasında sürükle-bırak için kullanılacak palet öğeleri.
 * Takvimio/MEB belirli gün ve haftalar + öğretmen işleri listesi.
 */

export const BELIRLI_PALETTE: string[] = [
  'Uluslararası Temiz Hava Günü',
  'İlköğretim Haftası',
  'Dünyayı Temizlik Günü (7 Eylül)',
  'Mevlid-i Nebî Haftası',
  'Gaziler Günü',
  'Türk Dil Bayramı',
  'Disleksi Haftası',
  'Dünya Disleksi Günü',
  'Hayvanları Koruma Günü',
  'Ahilik Kültürü Haftası',
  'Dünya Afet Azaltma Günü',
  'Birleşmiş Milletler Günü',
  'Cumhuriyet Bayramı',
  'Kızılay Haftası',
  'Organ Bağışı ve Nakli Haftası',
  'Lösemili Çocuklar Haftası',
  'Atatürk Haftası',
  'Afet Eğitimi Hazırlık Günü',
  'Dünya Diyabet Günü',
  'UNESCO Kuruluş Günü',
  'Dünya Felsefe Günü',
  'Dünya Çocuk Hakları Günü',
  'Ağız ve Diş Sağlığı Haftası',
  'Öğretmenler Günü',
  'Dünya Engelliler Günü',
  'Dünya Madenciler Günü',
  'Türk Kadınına Seçme ve Seçilme Hakkının Verilişi',
  'Mevlana Haftası',
  'İnsan Hakları ve Demokrasi Haftası',
  'Tutum, Yatırım ve Türk Malları Haftası',
  "Mehmet Akif Ersoy'u Anma Haftası",
  'Yılbaşı',
  'Verem Eğitimi ve Propaganda Haftası',
  'Enerji Tasarrufu Haftası',
  'Çalışan Gazeteciler Günü',
  'Dünya Kanser Günü',
  'Güvenli İnternet Günü',
  'Sivil Savunma Günü',
  'Vergi Haftası',
  'Yeşilay Haftası',
  'Girişimcilik Haftası',
  'Dünya Kadınlar Günü',
  'Bilim ve Teknoloji Haftası',
  "İstiklâl Marşı'nın Kabulü ve Mehmet Akif Ersoy'u Anma Günü",
  "Çanakkale Zaferi ve Şehitleri Anma Günü",
  'Tüketiciyi Koruma Haftası',
  'Türk Dünyası ve Toplulukları Haftası',
  'Nevruz Bayramı',
  'Orman Haftası',
  'Dünya Meteoroloji Günü',
  'Dünya Tiyatrolar Günü',
  'Kütüphaneler Haftası',
  'Kanser Haftası',
  'Dünya Otizm Farkındalık Günü',
  'Dünya Sağlık Günü',
  'Kişisel Verileri Koruma Günü',
  'Turizm Haftası',
  'Dünya Fikrî Mülkiyet Günü',
  'Ulusal Egemenlik ve Çocuk Bayramı',
  "Kût'ül Amâre Zaferi",
  'Emek ve Dayanışma Günü',
  'Bilişim Haftası',
  'Trafik ve İlkyardım Haftası',
  'İş Sağlığı ve Güvenliği Haftası',
  'Karayolu Trafik Güvenliği Günü',
  'Engelliler Haftası',
  'Vakıflar Haftası',
  'Anneler Günü',
  'Aile Günü',
  "Müzeler Haftası",
  "Atatürk'ü Anma ve Gençlik ve Spor Bayramı",
  "Etik Günü",
  "İstanbul'un Fethi",
  'Hayat Boyu Öğrenme Haftası',
  'Dünya Çevre Günü',
  'Çevre ve İklim Değişikliği Haftası',
  'Babalar Günü',
];

export const OGRETMEN_PALETTE: Array<{ title: string; path: string }> = [
  { title: 'Öğretmenler Kurulu', path: '/duty' },
  { title: 'Zümre Tutanakları', path: '/evrak' },
  { title: 'Yıllık Planlar', path: '/evrak' },
  { title: 'BEP Programı', path: '/evrak' },
  { title: 'Kulüp Planları', path: '/evrak' },
  { title: 'Şeflik Planlar', path: '/evrak' },
  { title: 'Kazanım Ara', path: '/evrak' },
  { title: 'Öğretmen Ağı', path: '/profile' },
  { title: 'Günlük Planlar', path: '/evrak' },
  { title: 'Kulüp Raporu', path: '/evrak' },
  { title: 'Şeflik Raporu', path: '/evrak' },
  { title: 'Sınav Hazırla', path: '/evrak' },
  { title: 'Soru Üret', path: '/evrak' },
  { title: 'Sınav Analizleri', path: '/evrak' },
  { title: 'Performans Değerlendir', path: '/evrak' },
  { title: 'Veli Toplantıları', path: '/evrak' },
  { title: 'Proje Asistanı', path: '/evrak' },
  { title: 'İdareye Teslim Evraklar', path: '/evrak' },
];
