/**
 * Okul değerlendirmeleri — varsayılan engellenen ifadeler (Türkçe + okul/öğrenci bağlamı).
 * Canlıda `app_config.school_reviews_content_rules` ile güncellenir (en fazla 300 satır).
 * Alt dizi eşleşmesi; yanlış pozitif riski taşıyan çok kısa diziler eklenmedi.
 */
export const DEFAULT_SCHOOL_REVIEWS_BLOCKED_TERMS: string[] = [
  // — Küfür / argo (yaygın varyantlar)
  'amk',
  'a.q',
  'aq',
  'mk',
  'amına',
  'amina',
  'amcık',
  'amcik',
  'oç',
  'orospu',
  'orospu çocuğu',
  'orospu cocugu',
  'piç',
  'pic',
  'pezevenk',
  'pezevengin',
  'kahpe',
  'siktir',
  'sikerim',
  'sikerler',
  'sikeyim',
  'sikiyim',
  'siktiğim',
  'siktigim',
  'siktiğimin',
  'siktigimin',
  'siktimin',
  'siktimin öküzü',
  'siktimin okuzu',
  'sikik',
  'sikko',
  'sik kafalı',
  'sik kafali',
  'siktiğimin öküzü',
  'siktigimin okuzu',
  'göt',
  'got',
  'götü',
  'gotu',
  'götveren',
  'gotveren',
  'götlek',
  'gotlek',
  'götüme',
  'gotume',
  'yarrak',
  'yarak',
  'taşak',
  'tasak',
  'taşağı',
  'tasagi',
  'boktan',
  'bok gibi',
  'sıçarım',
  'sicarim',
  'sıçayım',
  'sicayim',
  'ananı',
  'anani',
  'ananızı',
  'aninizi',
  'bacını',
  'bacini',
  'ananı si',
  'anani si',
  'bacını si',
  'bacini si',
  'ananı avradını',
  'anani avradini',
  'allah belanı',
  'allah belani',
  'belanı versin',
  'belani versin',
  'siktir git',
  'siktirgit',
  'siktir ol',
  'it oğlu',
  'it oglu',
  'yavşak',
  'yavsak',
  'şerefsiz',
  'serefsiz',
  'namussuz',
  'haysiyetsiz',
  'kahrolası',
  'kahrolasi',
  'lanet olsun',
  'şerefsiz herif',
  'serefsiz herif',
  'alçak',
  'alcak',
  'hıyar',
  'hiyar',
  'ibne',
  'domal',
  'fahişe',
  'fahise',
  'sürtük',
  'surtuk',
  'kaltak',
  'orospu evladı',
  'orospu evladi',
  'piç kurusu',
  'pic kurusu',
  'gavat',
  'kavat',
  'puşt',
  'pust',
  'dalyarak',
  'göt lalesi',
  'got lalesi',

  // — Okul / öğretmen / yönetim hedefli hakaret
  'öğretmen orospu',
  'ogretmen orospu',
  'öğretmen şerefsiz',
  'ogretmen serefsiz',
  'hoca manyak',
  'hoca salak',
  'müdür herif',
  'mudur herif',
  'okul müdürü şerefsiz',
  'okul muduru serefsiz',
  'müdür aptal',
  'mudur aptal',
  'okul boku',
  'okul bok gibi',
  'dershane uşağı',
  'dershane usagi',
  'nöbetçi salak',
  'nobetci salak',
  'veli manyağı',
  'veli manyagi',
  'sınıfın çöpü',
  'sinifin copu',
  'sınıf süzmesi',
  'sinif suzmesi',
  'mezun olamazsın',
  'mezun olamazsin',
  'notunu çaldım',
  'notunu caldim',

  // — Öğrenci / akran zorbalığı, aşağılama
  'eziksin',
  'ezik misin',
  'ezik herif',
  'ezik kız',
  'ezik kiz',
  'sıfır iq',
  'sifir iq',
  'sıfır zeka',
  'sifir zeka',
  'beyinsiz',
  'beyinsizsin',
  'gerizekalı',
  'gerizekali',
  'gerizekalısın',
  'gerizekalisin',
  'embesil',
  'embesilsin',
  'dangalak',
  'dangalaksın',
  'dangalaksin',
  'salak mısın',
  'salak misin',
  'aptal o',
  'aptalsın',
  'aptalsin',
  'mal mısın',
  'mal misin',
  'döl israfı',
  'dol israfi',
  'sütten çıkmış ak kaşık',
  'sutten cikmis ak kasik',
  'yenilmezmiş gibi',
  'nobrain',
  'no brain',
  'loser',
  'noob',
  'ezik loser',
  'ananı sik',
  'anani sik',
  'babanı sik',
  'babani sik',
  'sülaleni',
  'sulaleni',
  'köpeksin',
  'kopeksin',
  'şerefsiz köpek',
  'serefsiz kopek',
  'eşek gibisin',
  'essek gibisin',
  'öküz gibisin',
  'okuz gibisin',
  'çirkinsin',
  'cirkinsin',
  'çirkin herif',
  'cirkin herif',
  'şişko herif',
  'sisman herif',
  'iğrençsin',
  'igrencsin',
  'tiksinç birisin',
  'tiksinc birisin',
  'ibiş',
  'kızın çöp',
  'kizin cop',
  'oğlun piç',
  'oglun pic',
  'aşağılık herif',
  'asagilik herif',
  'aşağılık kız',
  'asagilik kiz',
  'sınıftan kov',
  'siniftan kov',
  'okuldan at',
  'okuldan kov',
  'disiplinle kov',
  'anne babana söyle',
  'anne babana soyle',
  'özürlü',
  'ozurlu',
  'salak öğrenci',
  'salak ogrenci',
  'en kötü öğrenci',
  'en kotu ogrenci',
  'sınıfın en kötüsü',
  'sinifin en kotusu',
  'çöpsün',
  'copsun',

  // — Şiddet / tehdit (okul ve genel)
  'öldüreceğim',
  'oldurecegim',
  'öldürürüm',
  'oldururum',
  'keserim',
  'kecerim',
  'döverim',
  'doverim',
  'vuracam',
  'vuracağım',
  'vuracagim',
  'burnunu kırarım',
  'burnunu kirarim',
  'okulu yak',
  'okulu bas',
  'bomba koy',
  'silahla',
  'bıçakla',
  'bicakla',
  'kes derini',
  'kanını içerim',
  'kanini icerim',

  // — Kendine zarar / intihar teşviki (öğrenci güvenliği)
  'intihar et',
  'intihar etmelisin',
  'öldür kendini',
  'oldur kendini',
  'kendini öldür',
  'kendini oldur',
  'kendine zarar ver',
  'kendine zarar',
  'kes bileklerini',
  'kes bilek',
  'zıpla çatıdan',
  'zipla catidan',
  'kys',
  'kill yourself',

  // — Cinsel taciz / istismar / ifşa (genç kullanıcılar)
  'sübyancı',
  'subyanci',
  'tecavüz',
  'tecavuz',
  'tecavüzcü',
  'tecavuzcu',
  'pedofil',
  'pedofili',
  'zoofil',
  'cinsel istismar',
  'taciz ediyorum',
  'tecavüz ederim',
  'tecavuz ederim',
  'çıplak foto',
  'ciplak foto',
  'çıplak at',
  'ciplak at',
  'ifşa edeceğim',
  'ifsa edecegim',
  'ifşa ettim',
  'ifsa ettim',
  'rezil ettim',
  'gizli çektim',
  'gizli cektim',
  'rızası yok',
  'rizasi yok',
  'zorla dokun',

  // — Nefret söylemi / ayrımcılık (genel)
  'ırk üstün',
  'irk ustun',
  'ırkçılık',
  'irkcilik',
  'n-word',
  'n word',
  'nazi',
  'hitler',
  'holokost yok',
  'holocaust yok',

  // — İngilizce yaygın küfür (öğrenci arası)
  'fuck you',
  'fuck off',
  'fucking',
  'shit',
  'bitch',
  'asshole',
  'bastard',
  'motherfucker',
  'dick',
  'pussy',
  'slut',
  'whore',
  'retard',
  'faggot',
  'nigger',

  // — Siber zorbalık / dolandırıcılık ima
  'hesabını çaldım',
  'hesabini caldim',
  'şifreni ver',
  'sifreni ver',
  'adresini ver',
  'ev adresin',
];
