/** Web geniş ayarları — tek JSON ile saklanır (web_extras_config). Bakım politikası: `docs/GUNCELLEME_VE_BAKIM_POLITIKASI.md`. */
export const DEFAULT_WEB_EXTRAS = {
  gtm_id: null as string | null,
  ga4_measurement_id: null as string | null,
  maintenance_enabled: false,
  maintenance_message_html: null as string | null,
  /** Tam eşleşme: bu path’ler bakım sırasında açık kalır */
  maintenance_allowed_exact: [
    '/login',
    '/register',
    '/bakim',
    '/favicon.ico',
    '/robots.txt',
    '/sitemap.xml',
  ],
  /** Path bu prefix’lerden biriyle başlıyorsa bakımda açık */
  maintenance_allowed_prefixes: [
    '/api',
    '/_next',
    '/dashboard',
    '/web-ayarlar',
    '/reklamlar',
    '/hosgeldin-mesajlari',
    '/settings',
    '/profile',
    '/schools',
    '/users',
    '/haberler',
    '/bildirimler',
    '/support',
    '/market',
    '/tv',
    '/evrak',
    '/modules',
    '/moderation',
    '/document-templates',
    '/extra-lesson-params',
    '/favoriler',
    '/kazanim-takip',
    '/duty',
    '/optik-formlar',
    '/akilli-tahta',
    '/bilsem',
    '/akademik-takvim',
    '/ogretmen-ajandasi',
    '/okul-degerlendirmeleri',
    '/school-profile',
    '/send-announcement',
    '/system-announcements',
    '/work-calendar',
    '/yillik-plan-icerik',
    '/outcome-sets',
    '/market-policy',
    '/school-reviews-settings',
    '/sinav-gorevleri',
    '/optik-okuma-ayarlar',
    '/akademik-takvim-sablonu',
    '/bilsem-sablon',
    '/school-reviews',
    '/storage',
  ],
  cache_ttl_yayin_seo: 300,
  cache_ttl_web_public: 300,
  cache_ttl_legal_pages: 120,
  /** GET /content/web-extras Cache-Control max-age (sn) */
  cache_ttl_web_extras: 30,
  global_robots_noindex: false,
  default_og_image_url: null as string | null,
  recaptcha_site_key: null as string | null,
  pwa_short_name: 'Öğretmen Pro',
  theme_color: '#0f172a',
  favicon_url: null as string | null,
  app_store_url: null as string | null,
  play_store_url: null as string | null,
  help_center_url: null as string | null,
  /** Reklam API ana şalteri (web; GET /ads-public boş döner) */
  ads_enabled: true,
  /**
   * Web: consent_mode=targeting reklamlar yalnızca çerez kabulü açıkken.
   * İstemci cookie_consent=accepted göndermeli (KVKK / ePrivacy uyumu).
   */
  ads_web_targeting_requires_cookie_consent: true,
} as const;
