/** Öğretmen hoşgeldin — örnek öz paket (önce öncelik). */
export const WELCOME_CURATED: readonly string[] = [
  'Güneş sana gelmiyorsa, sen güneşe gidersin.',
  'Bazı şeyleri satın alamazsın; kazanman gerekir. Bazı şeyleri hemen kazanamazsın; uğruna savaşman ve yaşaman gerekir.',
  'Beklersen sadece sana geleni alırsın; gidersen istediğin her şeyi.',
  'Hayat, insanın cesaretine göre büyür veya küçülür. — Anais Nin',
  'Yüzüstü yere serilseniz bile hâlâ ileriye doğru hareket ediyorsunuzdur. — Victor Kiam',
  'Amacımız imkânsızı mümkün, mümkünü kolay, kolayı da zarif ve zevkli yapmanın yollarını bulmaktır. — Dr. Feldenkrais',
  'Varlık elde etmek için yokluk gerek. Mimar ev yapmak için boş arsa arar. Yokluğa dikkat et, onda çok hikmetler vardır. — Mevlana',
  'Yeteri kadar nedeniniz varsa, her şeyi yapabilirsiniz. — Jim Rohn',
  'Önce FARKI yaratırsın, sonra da FARK yaratırsın. — Tayfun Topaloğlu',
  'İlk önce kendine ne olacağını sor; sonra ne yapmak gerekiyorsa yap. — Epiktetos',
  'Hayat bir bisiklete binmek gibidir. Pedalı çevirmeye devam ettiğiniz sürece düşmezsiniz.',
  'Derin anlamlar taşıyan hedeflerle motive olduğumuzda gerçekten yaşarız. — Greg Anderson',
  'İnsana olanlar değil, o insanın içinde olanlar önemlidir. — Louis Mann',
  'Yüzüne kapatılan kapılar ile kararlılığın, arkandan kapatılan kapılar ile cesaretin test edilir. — Tayfun Topaloğlu',
  'Yalnız işsiz olanlar değil; daha iyisini yapabilecekken yapmayanlar da başı boştur. — Sokrates',
  'Batan güneş için ağlamayın; yeniden doğduğunda ne yapacağınıza karar verin. — Dale Carnegie',
  'İnsanın hayatta güçlü olması önemli değil, kendini güçlü hissetmesi önemlidir. — Into the Wild',
  'Daha önce hiç sahip olmadığın bir şeye sahip olmak istiyorsan, daha önce hiç yapmadığın bir şey yapmalısın. — N. Peseschkian',
  'Dünyanın düşleyenlere de ihtiyacı var, yapanlara da; ama düşlediğini yapanlara daha çok. — S. Breathnach',
  'Başarısızlık, yeniden ve daha zekice başlayabilme fırsatından başka bir şey değildir.',
  'Bir şey yap, güzel olsun. Çok mu zor? Güzel bir şey söyle. Dilin mi dönmüyor? Güzel bir şey gör veya yaz. Beceremez misin? Güzel bir şeye başla. — Şems-i Tebrizi',
  'Hiç kimse sizin izniniz olmadan size kendinizi değersiz hissettiremez.',
  'Motivasyon yakıt olarak, amaç depo; vizyonla yola çıkar ve eylemle kendini gerçekleştirir. — Pat Mesiti',
  'İnciler kumsalda bulunmaz; bir tane istiyorsan onun için dalmalısın. — Çin atasözü',
  'Asla pişman olmayın! Sonuç iyiyse mükemmel; kötüyse bu bir tecrübedir. — Victoria Holt',
  'Başlamak için mükemmel olmak zorunda değilsin; mükemmel olmak için başlamak zorundasın. — Zig Ziglar',
  'Öfkeyi sevgiyle, kötülüğü iyilikle yen. Açgözlülüğü cömertlikle, yalanı gerçekle yen. — Buddha',
  'Bazı yenilgilerin nedeni, işi yarıda bıraktıklarında başarıya ne kadar yakın olduklarını bilememektir. — Thomas Edison',
  'Hayatınızı ortaya koymazsanız, hayatınızı kazanamazsınız. — Friedrich Schiller',
  'Yazgıların en güzeli, tutkuyla yaptığın iş için sana para ödeniyor olmasıdır. — A. Maslow',
  'Hiçbir zaman başınızı eğmeyin; hayatı karşınıza alın ve tam gözünün ortasına bakın. — Helen Keller',
  'Geçmişte kim olduğunu bilmek istiyorsan şu ana bak; kim olacağını bilmek istiyorsan ne yaptığına bak. — Buddha',
  'Konu işlerin yürütülmesine gelince motivasyon her şeydir. — Lee Iacocca',
  'Kaybedeceğini bile bile neden mücadele ediyorsun dedi. Öleceğini bildiği halde yaşadığını unutmuştu. — G. G. Márquez',
  'En iyinin dışında bir şey kabul etmeyenlere genellikle en iyiyi verir yaşam. — W. Somerset Maugham',
  'Bir gün değil, her gün istersen olur. — Tayfun Topaloğlu',
  'Keskin bıçak olmak için çok çekiç yemek gerekir. — Türk atasözü',
  'Uçurtmalar rüzgar gücüyle değil, o güce karşı koydukları için yükselirler. — Winston Churchill',
  'Amacına ulaşmak için hiçbir şeyi küçümseme; tam ulaşamazsan bile dene. Hepimizin güvenini bağladığımız o “belki” umudun ta kendisidir. — Dostoyevski',
  'Ne kazandığın başarılarda takılı kal ne de hatalarında ısrar et; şimdinin her değerli anında yeniden başla. — N. Donald Walsch',
  'Sen yolunda yürü… Bırak ne derlerse desinler. — Dante Alighieri',
  'Sadece güneşli günlerde yürürsen hedefe ulaşamazsın.',
  'Uçamıyorsan koş; koşamıyorsan yürü; yürüyemiyorsan sürün; ama hareket etmeye devam et. — Martin Luther King Jr.',
  'Ya kaybettiklerin üzerine yoğunlaşırsın ya da geriye kalanlar için savaşırsın.',
  'Hiçbir şey ayağınıza gelmez; iyi olan hiçbir şey değil. Her şeyi gidip kendiniz almanız gerekir. — George Bernard Shaw',
  'Henüz hedeflediğim yerde olmayabilirim; ama dün olduğum yerden daha yakınım.',
  'Yolunu değiştirmeden devam ettiğin sürece ne kadar yavaş gittiğinin önemi yoktur. — Konfüçyüs',
  'Hiçbir şeyden asla vazgeçme; vazgeçenler yalnızca kaybedenlerdir. — Abraham Lincoln',
  'Ne kadar ileri gidebileceğini ancak çok uzağa gitmeye cesaret edenler keşfedebilir. — T. S. Eliot',
  'Ne zaman ki güçlü olmak tek çare olarak kalır, o zaman anlarsın ne kadar güçlü olduğunu. — Bob Marley',
  'Bazı insanlar olmasını ister, bazıları bekler, bazıları ise oldurur. — Michael Jordan',
];
