/** Öğretmen paneli için ek özlü / aforizma (Türkçe, kısa). Kaynak: klasik alıntılar, eğitim ve yaşam bilgeliği. */
export const WELCOME_DUSUNCE_EK: readonly string[] = [
  'Kendini bilmek, bilgeliğin başlangıcıdır. — Aristoteles',
  'Sorgulanmayan yaşam yaşanmaya değer değildir. — Sokrates',
  'Aynı nehirde iki kez yıkanılmazsın. — Heraklit',
  'Düşünüyorum, o halde varım. — René Descartes',
  'Dünyada görmek istediğin değişimin ta kendisi ol. — Mahatma Gandhi',
  'Bilim bildiklerin, felsefe bilmediklerindir. — Bertrand Russell',
  'Cesaret, korkunun olmaması değil, korkunun üstesinden gelmektir. — Nelson Mandela',
  'Başarı son değil, başarısızlık ölümcül değil; önemli olan devam etmektir. — Winston Churchill',
  'Bildiğim tek şey, hiçbir şey bilmediğimdir. — Sokrates',
  'Mutluluk, aranan bir şey değil, bulunan bir şeydir. — Lev Tolstoy',
  'İnsan ancak kendine yabancılaştığında yabancılaşır. — Erich Fromm',
  'Özgürlük, seçilmiş zorunluluktur. — Jean-Paul Sartre',
  'Küçük adımlar büyük yolculukları başlatır. — Lao Tzu',
  'Bin millik yol tek adımla başlar. — Lao Tzu',
  'Okumak ruhun gıdasıdır. — Cicero',
  'Erdem bilgiyle birlikte gelir. — Platon',
  'Mutluluk faaliyettedir. — Aristoteles',
  'Az konuş, çok dinle. — Sokrates',
  'Hata insana mahsustur. — Seneca',
  'Sanat uzun, ömür kısa. — Hippocrates',
  'Zaman her şeyin ilacıdır. — Menandros',
  'İyi başlangıç işin yarısıdır. — Platon',
  'Vakit nakittir. — Benjamin Franklin',
  'Küçük fırsatlar büyük işlerin başlangıcıdır. — Demostenes',
  'Başlamak bitirmenin yarısıdır. — Horatius',
  'Azim, yeteneği yener. — William Faulkner',
  'Kalite bir alışkanlıktır. — Aristoteles',
  'Hedefsiz gemiye rüzgâr yetmez. — Thomas Carlyle',
  'İrade, karakterin sesidir. — Ralph Waldo Emerson',
  'Hayal gücü bilgiden daha önemlidir. — Albert Einstein',
  'Merak bilgeliğin başlangıcıdır. — Albert Einstein',
  'Sorunları çözmek için düşünmek gerekir. — Albert Einstein',
  'Tecrübe, yanlışların adıdır. — Oscar Wilde',
  'Dürüstlük en kısa yoldur. — William Shakespeare',
  'Sabır, zamanı yenmenin yoludur. — Leo Tolstoy',
  'Sessizlik bazen en güçlü cevaptır. — Mahatma Gandhi',
  'Paylaşmak çoğaltmaktır. — Antoine de Saint-Exupéry',
  'Özür, cesaretin parçasıdır. — Benjamin Franklin',
  'Dinlemek, sevmenin yarısıdır. — Mevlana Celaleddin Rumi',
  'Merhamet insanı yüceltir. — Seneca',
  'Tevazu bilgelik işaretidir. — Konfüçyüs',
  'Kitap sessiz öğretmendir. — Cicero',
  'Soru, öğrenmenin anahtarıdır. — Albert Einstein',
  'Hata, öğrenmenin ücretidir. — John Powell',
  'Tekrar ustayı doğurur. — Türk atasözü',
  'Pratik mükemmelleştirir. — Robert Glaser',
  'Yavaş ama sürekli kazanır. — Konfüçyüs',
  'Alışkanlık kaderi yazar. — Horatius',
  'Seçimler seni tanımlar. — Seneca',
  'Zamanı iyi kullan. — Seneca',
  'Enerjini koru. — Marcus Aurelius',
  'Hedef net olunca yol açılır. — Seneca',
  'Öncelik netliği getirir. — Greg McKeown',
  'Derin nefes, net düşünce. — Thich Nhat Hanh',
  'Uyku, zekânın tamircisidir. — Matthew Walker',
  'Hareket depresyonu kovar. — John Ratey',
  'Sessizlik iç sesi duyurur. — Rumi',
  'Yazmak düşünceyi netleştirir. — Paul Graham',
  'Bitir; başlamak yetmez. — Robin Sharma',
  'Teslim tarihi disiplindir. — anonim',
  'Standart yükseltir. — Jocko Willink',
  'Yenilik cesaret ister. — Peter Drucker',
  'Risk, büyümenin kapısıdır. — John C. Maxwell',
  'Güven inşa edilir. — Stephen Covey',
  'Saygı karşılıklıdır. — anonim',
  'Hayır demek, evet demektir (önceliğe). — Derek Sivers',
  'Zaman blokları verim getirir. — Cal Newport',
  'Derin iş, yüzeysel gürültüyü yener. — Cal Newport',
  'Tek görev, tek odak. — Cal Newport',
  'Küçük zaferler büyük motivasyondur. — Teresa Amabile',
  'Ölç, yönet. — Peter Drucker',
  'İnsan kaynağı en değerli kaynaktır. — Peter Drucker',
  'Müşteri işin kalbidir. — Peter Drucker',
  'Lider önce dinler. — Simon Sinek',
  'Takım, bireyden büyüktür. — Phil Jackson',
  'Şeffaflık güven doğurur. — Ray Dalio',
  'İletişim köprüdür. — Paul Watzlawick',
  'Net konuş, net anlaşıl. — anonim',
  'Geri bildirim hediyedir. — Kim Scott',
  'Eleştiri iyileştirme fırsatıdır. — Bill Gates',
  'Kutlama motivasyonu besler. — Shawn Achor',
  'Mola verimlilik getirir. — Tony Schwartz',
  'Denge sürdürülebilirliktir. — James Clear',
  'Uzun vade kısa telaşı yener. — Jeff Bezos',
  'Sabır bileşik getiri sağlar. — Warren Buffett',
  'Kimliğin hedefinden önce gelir. — James Clear',
  'Sistem hedeften önemlidir. — James Clear',
  'Tutarlılık otorite doğurur. — Robert Cialdini',
  'Örnek olmak en güçlü ders. — Albert Schweitzer',
  'Öğretmek öğrenmektir. — Seneca',
  'Her öğrenci bir dünyadır. — anonim',
  'Merak ateşi yak. — Carl Sagan',
  'Cevap basit olabilir. — Richard Feynman',
  'Karmaşıklığı parçala. — George Pólya',
  'Hikâye akılda kalır. — Chip Heath',
  'İlham ikna eder. — Simon Sinek',
  'Sertlik değil, netlik. — Kim Malone Scott',
  'Adalet sınıfta barıştır. — John Dewey',
  'Kurallar özgürlük verir. — Immanuel Kant',
  'Beklenti netliği getirir. — Doug Lemov',
  'Net beklenti, net sonuç. — anonim',
  'Zamanlayıcı ertelemeyi kırar. — Francesco Cirillo',
  'Bir sonraki eylem net olmalı. — David Allen',
  'Dikkat en değerli sermayedir. — Cal Newport',
  'Bildirimleri sustur; odaklan. — Tristan Harris',
  'Gece uyku, gündüz netlik. — Matthew Walker',
  'Yürüyüş fikir doğurur. — Friedrich Nietzsche',
  'Müzik ruhu ayarlar. — Platon',
  'Boşluk fikir doğurur. — Lao Tzu',
  'Kısıt yaratıcılık üretir. — Austin Kleon',
  'Az ama öz. — Ludwig Mies van der Rohe',
  'Seçmek bırakmaktır. — Seneca',
  'Eisenhower matrisi kurtarır. — Dwight Eisenhower',
  'Acil, önemli değildir. — Dwight Eisenhower',
  'Hazırlık şansı çağırır. — Louis Pasteur',
  'Şans hazırlıkla buluşunca başarı olur. — Seneca',
  'Emek görünür olur. — anonim',
  'İnat değil, azim. — Angela Duckworth',
  'Esneklik kırılmazlık verir. — Carol Dweck',
  'Değişim fırsattır. — John F. Kennedy',
  'Kriz yenilik doğurur. — Yuval Noah Harari',
  'Sistem düşün. — Donella Meadows',
  'Kök neden ara. — Sakichi Toyoda',
  'Tekrarlanabilir süreç kur. — W. Edwards Deming',
  'Hızlı öğren, hızlı düzelt. — Reid Hoffman',
  'Iterasyon kalite getirir. — Kent Beck',
  'Veri konuşsun. — W. Edwards Deming',
  'Hipotez kur, test et. — Karl Popper',
  'Plato tepe noktasıdır; vadide kalma. — anonim',
  'Yardım istemek güçtür. — Brené Brown',
  'Mentorluk ver, al. — Eric Schmidt',
  'Topluma katkı anlam verir. — Viktor Frankl',
  'Anlam seçilir. — Viktor Frankl',
  'Umut iyileştirir. — Christopher Peterson',
  'İyimserlik stratejidir. — Simon Sinek',
  'Mizah gerilimi kırar. — John Cleese',
  'Kibarlık asalettir. — Baltasar Gracián',
  "İlim Çin'de bile olsa alınız. — Hz. Muhammed",
  'Temizlik imandandır. — Hz. Muhammed',
  'İyilik kötülüğü yener. — Martin Luther King Jr.',
  'Barış güçtür. — Nelson Mandela',
  'Hürriyet mesuliyettir. — Mustafa Kemal Atatürk',
  'Gençlik! İstikbalin sahibi sizsiniz. — Mustafa Kemal Atatürk',
  'Öğretmenler! Yeni nesli sizler yetiştireceksiniz. — Mustafa Kemal Atatürk',
  'Hayatta en hakiki mürşit ilimdir. — Mustafa Kemal Atatürk',
  'Sanatsız kalan bir milletin hayat damarlarından biri kopmuş demektir. — Mustafa Kemal Atatürk',
  'Yorulmadan çalışmak, yorulmadan okumak gerekir. — Mustafa Kemal Atatürk',
  'Bütün ümidim gençliktedir. — Mustafa Kemal Atatürk',
  'Cumhuriyet fazilettir. — Mustafa Kemal Atatürk',
  'Ne mutlu Türküm diyene! — Mustafa Kemal Atatürk',
  'Yükselen yeni nesil, istikbalin güvencesidir. — Mustafa Kemal Atatürk',
  'Öğrenmek için yaşlanmak gerekmez; yaşlanmak için öğrenmek gerekir. — Henry Ford',
  'Düşün, sonra konuş. — Konfüçyüs',
  'Bilgi güçtür. — Francis Bacon',
  'İmkânsız, tembelin sözlüğünde yazılı tek kelimedir. — Mustafa Kemal Atatürk',
  'Yurtta sulh, cihanda sulh. — Mustafa Kemal Atatürk',
  'Ben sporcunun zekâsını, bedenini, ahlakını överim. — Mustafa Kemal Atatürk',
  'Hayatta en gerçek yol gösterici bilimdir. — Mustafa Kemal Atatürk',
  'Türk milleti zekidir; Türk milleti çalışkandır. — Mustafa Kemal Atatürk',
  'Egemenlik kayıtsız şartsız milletindir. — Mustafa Kemal Atatürk',
  'Korku, cesaretin gölgesidir. — Ambrose Redmoon',
  'Bugün küçük, yarın büyük. — James Clear',
  'İlerle, durma. — Marcus Aurelius',
  'Disiplin özgürlük satın alır. — Jocko Willink',
  'Basit tut, ilerle. — anonim',
  'Güneşe çık, içini aydınlat. — anonim',
  'Doğa sakinlik verir. — John Muir',
  'Liste, zihni rahatlatır. — David Allen',
  'Kalite küçük ayrıntıdadır. — Michelangelo',
  'Rutin güven verir. — Atul Gawande',
  'Denemek öğretir. — Samuel Beckett',
  'Korku sınır çizer; cesaret aşar. — anonim',
  'Sınır koymak sağlıktır. — Henry Cloud',
  'Evet demek odaktır. — Derek Sivers',
  'Ölçeklenebilir düşün. — Reid Hoffman',
  'Geri alınabilir adım at. — Jeff Bezos',
  'Küçük risk al. — Seth Godin',
  'Öğrenme eğrisi normaldir. — Josh Kaufman',
  'Birlikte daha iyiyiz. — Helen Keller',
  'Mentor bul. — Eric Schmidt',
  'Gönüllülük büyütür. — Mahatma Gandhi',
  'Anlam sürdürür. — Viktor Frankl',
  'Denge akıldır. — Aristoteles',
  'Nezaket güçtür. — Larry King',
  'Hoşgörü köprüdür. — Héctor Abad Faciolince',
  'Hakikat ışıktır. — Sofokles',
  'Adalet denge demektir. — Platon',
  'Mesuliyet özgürlük getirir. — Jordan Peterson',
  'Standart yükselt. — Jocko Willink',
  'Erken kalk. — Benjamin Franklin',
  'Planla, uygula, gözden geçir. — W. Edwards Deming',
  'Sürekli iyileştirme. — Masaaki Imai',
  'Küçük adım, büyük etki. — Kaizen ilkesi',
  'Israfı azalt. — Taiichi Ohno',
  'Değer akışı düşün. — Lean ilkesi',
  '5S düzen getirir. — anonim',
  'Görsel yönetim netlik verir. — anonim',
  'Checklist pilotların silahıdır. — Atul Gawande',
  'Güvenlik önce gelir. — anonim',
  'Sağlık sermayedir. — Ralph Waldo Emerson',
  'Beslenme enerjidir. — Michael Pollan',
  'Su iç, zihin açılır. — anonim',
  'Nefes kontrolü sakinlik getirir. — James Nestor',
  'Şükür mutluluğu büyütür. — Robert Emmons',
  'Minnettarlık beyin değiştirir. — Rick Hanson',
  'Günlük tut, netleş. — Marcus Aurelius',
  'Akşam değerlendir, sabah net başla. — Benjamin Franklin',
  'Haftalık gözden geçir. — David Allen',
  'Çeyrek hedef netleştirir. — John Doerr',
  'Sezgi veriyi tamamlar. — Daniel Kahneman',
  'Deney aç. — Eric Ries',
  'Öğrenme ömür boyu sürer. — UNESCO',
  'Öğretmen, geleceği inşa eder. — Mustafa Kemal Atatürk',
  'Her gün yeni bir sayfa. — Marcus Aurelius',
  'Cesur ol; küçük adım at. — Mary Anne Radmacher',
  'İyi niyet yolu açar. — Seneca',
  'Dürüstlük uzun vadede kazanır. — Warren Buffett',
  'İtibar sermayedir. — Warren Buffett',
  'Sözün altındır. — Türk atasözü',
  'Az vaat, çok teslim. — anonim',
  'Beklentiyi yönet. — Peter Drucker',
  'Net ol, nazik ol. — Kim Scott',
  'Vazgeçmek bazen ilerlemektir. — Seth Godin',
  'Fırsat maliyeti her yerde. — Paul Samuelson',
  'Zaman geri dönmez. — Benjamin Franklin',
  'Bugünün işi bugün. — Benjamin Franklin',
  'Erteleme düşmandır. — Seneca',
  'İlk adım en zoru. — Mark Twain',
  'Başla, düzelt. — Reid Hoffman',
  'Yeterince iyi hızlı ilerletir. — Sheryl Sandberg',
  'Geri bildirim altın değerindedir. — Bill Gates',
  'Kritik düşün, nazik ol. — Daniel Dennett',
  'Fikir ayrılığı saygıyla. — Adam Grant',
  'Çatışma fırsattır. — Crucial Conversations',
  'Uzlaş çözüm getirir. — Roger Fisher',
  'Ortak zemin ara. — William Ury',
  'Dinle anlamak için. — Stephen Covey',
  'Anlamadan cevap verme. — Epiktetos',
  'Soru derinleştirir. — Neil Postman',
  'Cevap basitleştirir. — Albert Einstein',
  'Özet netlik getirir. — Barbara Minto',
  'Görsel düşün. — Dan Roam',
  'Modelle. — George Box',
  'Simüle et. — Claude Shannon',
  'Deney yap. — Richard Feynman',
  'Ölç, öğren. — Eric Ries',
  'Tekrarla. — Anders Ericsson',
  'Ölçekle. — Reid Hoffman',
  'Sürdür. — Yvon Chouinard',
];
