/** Kısa Türk atasözleri (yaygın gelenek; eğitim ve yaşam öğüdü). */
const RAW: readonly string[] = [
  'Ağaç yaşken eğilir',
  'Damlaya damlaya göl olur',
  'İşleyen demir pas tutmaz',
  'Acele işe şeytan karışır',
  'Sakla samanı gelir zamanı',
  'Ayağını yorganına göre uzat',
  'Bin bilsen de bir bilene danış',
  'Önce düşün sonra söyle',
  'Boş çuval ayakta durmaz',
  'Bir elin nesi var iki elin sesi var',
  'Zorla güzellik olmaz',
  'Ağır kazan geç kaynar',
  'Tok ne bilir açın halinden',
  'Ne ekersen onu biçersin',
  'Bugünün işini yarına bırakma',
  'Bakarsan bağ olur bakmazsan dağ olur',
  'Dağ dağa kavuşmaz insan insana kavuşur',
  'Dost kara günde belli olur',
  'El elden üstündür',
  'Gözden ırak olan gönülden de ırak olur',
  'Anlayana sivrisinek saz anlamayana davul zurna az',
  'Arife tarif gerekmez',
  'Ateş düştüğü yeri yakar',
  'Ateş olmayan yerden duman çıkmaz',
  'Bana arkadaşını söyle sana kim olduğunu söyleyeyim',
  'İki gönül bir olursa samanlık seyran olur',
  'Ak akçe karagün içindir',
  'Araba devrilince yol gösteren çok olur',
  'Davulun sesi uzaktan hoş gelir',
  'Akıl için yol birdir',
  'Can boğazdan gelir',
  'Gülme komşuna gelir başına',
  'Erken kalkan yol alır',
  'Kaz gelecek yerden tiftik dökülmez',
  'Dikensiz gül olmaz',
  'Suyu olmayan yerde ot bitmez',
  'Balık baştan kokar',
  'Al malın iyisini çekme kaygısını',
  'Vakit nakittir',
  'Derdini söylemeyen derman bulamaz',
  'Sırrını verme dostuna o da söyler dostuna',
  'Kurunun yanında yaş da yanar',
  'Zararın neresinden dönülse kârdır',
  'Üzüm üzüme baka baka kararır',
  'Dimyata pirince giden evdeki bulgurdan olur',
  'Bir fincan kahvenin kırk yıl hatırı vardır',
  'Ağaç kökünden yıkılır',
  'Aç köpek fırın duvarını deler',
  'Bir başa bir göz yeter',
  'İnsanoğlu çiğ süt emmiş',
  'Yaş yetmiş iş bitmiş',
  'Ağır git ki yol alasın',
  'Sabah ola hayır ola',
  'Almak kolay ödemek güçtür',
  'İki el bir baş içindir',
  'Kalpten kalbe yol vardır',
  'Can tümceden aziz',
  'İki at bir kazığa bağlanamaz',
  'Ata arpa yiğide pilav',
  'Atın ölümü arpadan olsun',
  'At sahibine göre eşer',
  'At binicisini tanır',
  'At yiğidin yoldaşıdır',
  'Atına bakan ardına bakmaz',
  'Atılan ok geri dönmez',
  'Avcı ne kadar hile bilse ayı o kadar yol bilir',
  'Arı bal alacak çiçeği bilir',
  'Arı kızdıranı sokar',
  'Arı gibi eri olanın dağ kadar yeri olur',
  'Altın ateşte insan mihnette belli olur',
  'Altının kıymetini sarraf bilir',
  'Altın yere düşmekle pul olmaz',
  'Alçak yer yiğidi hor gösterir',
  'Alçak uçan yüce konar yüce uçan alçak konar',
  'Aman diyene kılıç kalkmaz',
  'Alma mazlumun ahını çıkar aheste aheste',
  'Almadan vermek Allah’a mahsus',
  'Alna yazılan başa gelir',
  'Alt değirmen güçlü akar',
  'Ateş demekle ağız yanmaz',
  'Arayan Mevlasını da bulur belasını da',
  'Arslan yattığı yerden belli olur',
  'Aslan kükrerse beygir titrer',
  'Asıl azmaz bal kokmaz',
  'At arıklıkta yiğit gariplikte',
  'At ile avrat yiğidin bahtına',
  'At ölür meydan kalır yiğit ölür şan kalır',
  'Atta karın yiğitte burun',
  'Atlıya saat olmaz',
  'Ağır yük atı yere indirir',
  'Akıl olmayınca ne yapsın sakal',
  'Akıllı düşman akılsız dosttan iyidir',
  'Akıllı düşmanından çok akılsız dostundan sakın',
  'Akıllı köprü arar deli suya atlar',
  'Sular bulanmadan durulmaz',
  'Üzümünü ye bağını sorma',
  'Taşıma suyla değirmen dönmez',
  'Her koyun kendi bacağından asılır',
  'İti an çomağı hazırla',
  'İş bitenin küfü yok',
  'Körün istediği bir göz aydınlık olsun',
  'Er geç ak alınır kara yazılır',
  'Er yatağından bellidir',
  'Erkek aslan aslan da dişi aslan aslan değil mi',
  'Eline sağlık diline de',
  'El elin eşeğini türkü çağırarak arar',
  'Ekmek aslanın ağzında',
  'Ekmek parası kolay kazanılmaz',
  'Ekmek yok kanun yok',
  'Ekmekle oynanmaz',
  'Dağ ne kadar yüce olsa yol üstünden aşar',
  'Dereyi geçerken at değiştirilmez',
  'Dost acı söyler',
  'Dost başa düşman ayağa bakar',
  'Dünya alış verişi yarı yolda bırakılmaz',
  'Düştükçe ders alınır',
  'Mum dibine ışık vermez',
  'Er ekmeği er kursağında kalmaz',
  'Büyük lokma ye büyük söz söyleme',
  'Çabuk parlayan çabuk söner',
  'Çalışmadan yemek yok',
  'Çıkmayan candan ümit kesilmez',
  'Dereyi görmeden paça sıvama',
  'Bu da geçer ya hu',
  'Boyundan büyük işe girme',
  'Borcu olan borcunu bilir',
  'Yuvayı dişi kuş yapar',
  'Yüzü gülenin çorbası kaynar',
  'Zahmetsiz rahmet olmaz',
  'Zorda kalana el uzat',
  'Yalancının mumu yatsıya kadar yanar',
  'Su akar yolunu bulur',
  'Söz gümüş ise sukut altındır',
  'Söz senettir',
  'Tencere yuvarlanmış kapağını bulmuş',
  'Bir elin verdiğini öteki el görmesin',
  'Böğüren öküz çifti kaçırır',
  'Bülbülü altın kafese koymuşlar ah vatanım demiş',
  'Ağaç ne kadar yüksek olsa yaprak yere düşer',
  'Balık sudan çıkmaz',
  'Değirmen suyuyla döner',
  'Defter açılırsa yüz kara çıkar',
  'Dert ortağı dertten kurtulmaz',
  'Dert büyükse dev büyük',
];

function uniqStrings(items: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of items) {
    const t = s.trim();
    if (!t || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  return out;
}

const ATAS_UNIQ = uniqStrings(RAW);

export const WELCOME_ATASOZU_EK_TAGGED: readonly string[] = ATAS_UNIQ.map((l) => {
  const base = l.endsWith('.') ? l.slice(0, -1) : l;
  return `${base}. — Türk atasözü`;
});
