import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const XLSX = require('xlsx');
import fs from 'fs';
const buf = fs.readFileSync('C:\\Users\\mehme\\OneDrive\\Desktop\\yiillik-plan-sablon.xlsx');
const wb = XLSX.read(buf, { type: 'buffer' });
const rows = XLSX.utils.sheet_to_json(wb.Sheets.Sayfa1, { header: 1, defval: '' });
const raw = rows[2][1];
const h = String(raw).replace(/\r?\n/g, ' ');
console.log('raw repr', JSON.stringify(raw));
console.log('h repr', JSON.stringify(h));
console.log('match', h.match(/(\d+)\s*\.\s*Hafta/i));
