/**
 * Defterdoldur / Takvimio / MEB tarzı hafta bazlı akademik takvim seed (2025-2026)
 * Kaynak: defterdoldur.com/site-haritasi, takvimio.com belirli gün ve haftalar, MEB çalışma takvimi
 *
 * Sadece web-admin academic-calendar-palette ile uyumlu öğeler eklenir (BELIRLI_ALLOWED, OGRETMEN_PATH).
 */

/** Site uyumlu belirli gün/hafta başlıkları – academic-calendar-palette.ts ile senkron tutulmalı. */
export const BELIRLI_ALLOWED: ReadonlySet<string> = new Set([
  'Uluslararası Temiz Hava Günü',
  'İlköğretim Haftası',
  'Dünyayı Temizlik Günü (7 Eylül)',
  'Mevlid-i Nebî Haftası',
  'Gaziler Günü',
  'Türk Dil Bayramı',
  'Disleksi Haftası',
  'Dünya Disleksi Günü',
  'Hayvanları Koruma Günü',
  'Ahilik Kültürü Haftası',
  'Dünya Afet Azaltma Günü',
  'Birleşmiş Milletler Günü',
  'Cumhuriyet Bayramı',
  'Kızılay Haftası',
  'Organ Bağışı ve Nakli Haftası',
  'Lösemili Çocuklar Haftası',
  'Atatürk Haftası',
  'Afet Eğitimi Hazırlık Günü',
  'Dünya Diyabet Günü',
  'UNESCO Kuruluş Günü',
  'Dünya Felsefe Günü',
  'Dünya Çocuk Hakları Günü',
  'Ağız ve Diş Sağlığı Haftası',
  'Öğretmenler Günü',
  'Dünya Engelliler Günü',
  'Dünya Madenciler Günü',
  'Türk Kadınına Seçme ve Seçilme Hakkının Verilişi',
  'Mevlana Haftası',
  'İnsan Hakları ve Demokrasi Haftası',
  'Tutum, Yatırım ve Türk Malları Haftası',
  "Mehmet Akif Ersoy'u Anma Haftası",
  'Yılbaşı',
  'Verem Eğitimi ve Propaganda Haftası',
  'Enerji Tasarrufu Haftası',
  'Çalışan Gazeteciler Günü',
  'Dünya Kanser Günü',
  'Güvenli İnternet Günü',
  'Sivil Savunma Günü',
  'Vergi Haftası',
  'Yeşilay Haftası',
  'Girişimcilik Haftası',
  'Dünya Kadınlar Günü',
  'Bilim ve Teknoloji Haftası',
  "İstiklâl Marşı'nın Kabulü ve Mehmet Akif Ersoy'u Anma Günü",
  "Çanakkale Zaferi ve Şehitleri Anma Günü",
  'Tüketiciyi Koruma Haftası',
  'Türk Dünyası ve Toplulukları Haftası',
  'Nevruz Bayramı',
  'Orman Haftası',
  'Dünya Meteoroloji Günü',
  'Dünya Tiyatrolar Günü',
  'Kütüphaneler Haftası',
  'Kanser Haftası',
  'Dünya Otizm Farkındalık Günü',
  'Dünya Sağlık Günü',
  'Kişisel Verileri Koruma Günü',
  'Turizm Haftası',
  'Dünya Fikrî Mülkiyet Günü',
  'Ulusal Egemenlik ve Çocuk Bayramı',
  "Kût'ül Amâre Zaferi",
  'Emek ve Dayanışma Günü',
  'Bilişim Haftası',
  'Trafik ve İlkyardım Haftası',
  'İş Sağlığı ve Güvenliği Haftası',
  'Karayolu Trafik Güvenliği Günü',
  'Engelliler Haftası',
  'Vakıflar Haftası',
  'Anneler Günü',
  'Aile Günü',
  "Müzeler Haftası",
  "Atatürk'ü Anma ve Gençlik ve Spor Bayramı",
  "Etik Günü",
  "İstanbul'un Fethi",
  'Hayat Boyu Öğrenme Haftası',
  'Dünya Çevre Günü',
  'Çevre ve İklim Değişikliği Haftası',
  'Babalar Günü',
  'Okul Öncesi Eğitim Haftası',
  'Oyun ve Oyuncak Haftası',
  'Meslek Eğitimi ve Teknoloji Haftası',
  'Çıraklık ve İşletmelerde Meslek Eğitimi Haftası',
  'Kaynaştırma ve Özel Eğitim Haftası',
  'Halk Eğitimi ve Kurs Haftası',
  'BILSEM ve Özel Yetenek Etkinlik Haftası',
  'İmam Hatip Okulları Etkinlik ve Değerler Haftası',
  'Okuma Kültürü ve Kitap Haftası',
  'Dünya Okul Öncesi Eğitim Günü',
  'Güvenli Okul ve Farkındalık Haftası',
  'Rehberlik ve Kariyer Haftası',
  'Meslek Tanıtım ve İşyeri Gezisi Haftası',
]);

/** Eski verilerdeki varyasyonlar → site uyumlu başlık (örn. "Dünyayı Temizlik Günü" → "Dünyayı Temizlik Günü (7 Eylül)") */
export const BELIRLI_NORMALIZE: Record<string, string> = {
  'Dünyayı Temizlik Günü': 'Dünyayı Temizlik Günü (7 Eylül)',
};

export const ACADEMIC_CALENDAR_2025_2026 = [
  { w: 0, title: 'Seminer Haftası & İlköğretim Uyum Haftası', start: '2025-09-01', end: '2025-09-08', belirli: ['Uluslararası Temiz Hava Günü', 'Dünyayı Temizlik Günü (7 Eylül)'], ogretmen: ['Öğretmenler Kurulu', 'Zümre Tutanakları', 'Yıllık Planlar', 'BEP Programı', 'Kulüp Planları', 'Şeflik Planlar', 'Kazanım Ara', 'Öğretmen Ağı'] },
  { w: 1, title: '1. Dönem Başlangıcı', start: '2025-09-08', end: '2025-09-12', belirli: ['Uluslararası Temiz Hava Günü', 'İlköğretim Haftası'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 2, title: null, start: '2025-09-15', end: '2025-09-19', belirli: ['İlköğretim Haftası', 'Dünyayı Temizlik Günü (7 Eylül)', 'Mevlid-i Nebî Haftası', 'Gaziler Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 3, title: null, start: '2025-09-22', end: '2025-09-26', belirli: ['Türk Dil Bayramı'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 4, title: null, start: '2025-09-29', end: '2025-10-03', belirli: ['Disleksi Haftası', 'Dünya Disleksi Günü', 'Hayvanları Koruma Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Kulüp Raporu', 'Şeflik Raporu'] },
  { w: 5, title: null, start: '2025-10-06', end: '2025-10-10', belirli: ['Ahilik Kültürü Haftası', 'Dünya Afet Azaltma Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Öğretmen Ağı'] },
  { w: 6, title: null, start: '2025-10-13', end: '2025-10-17', belirli: ['Birleşmiş Milletler Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Proje Asistanı'] },
  { w: 7, title: null, start: '2025-10-20', end: '2025-10-24', belirli: [], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Sınav Hazırla', 'Soru Üret'] },
  { w: 8, title: null, start: '2025-10-27', end: '2025-10-31', belirli: ['Cumhuriyet Bayramı', 'Kızılay Haftası'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Kulüp Raporu', 'Şeflik Raporu', 'Veli Toplantıları'] },
  { w: 9, title: null, start: '2025-11-03', end: '2025-11-07', belirli: ['Kızılay Haftası', 'Organ Bağışı ve Nakli Haftası', 'Lösemili Çocuklar Haftası'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Sınav Analizleri', 'Performans Değerlendir', 'Öğretmen Ağı'] },
  { w: 10, title: '1. Dönem Ara Tatili', start: '2025-11-10', end: '2025-11-14', belirli: ['Atatürk Haftası', 'Afet Eğitimi Hazırlık Günü', 'Dünya Diyabet Günü'], ogretmen: [] },
  { w: 11, title: null, start: '2025-11-17', end: '2025-11-21', belirli: ['Atatürk Haftası', 'UNESCO Kuruluş Günü', 'Dünya Felsefe Günü', 'Dünya Çocuk Hakları Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 12, title: null, start: '2025-11-24', end: '2025-11-28', belirli: ['Ağız ve Diş Sağlığı Haftası', 'Öğretmenler Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 13, title: null, start: '2025-12-01', end: '2025-12-05', belirli: ['Dünya Engelliler Günü', 'Dünya Madenciler Günü', 'Türk Kadınına Seçme ve Seçilme Hakkının Verilişi'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Öğretmen Ağı'] },
  { w: 14, title: null, start: '2025-12-08', end: '2025-12-12', belirli: ['Mevlana Haftası', 'İnsan Hakları ve Demokrasi Haftası'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 15, title: null, start: '2025-12-15', end: '2025-12-19', belirli: ['Tutum, Yatırım ve Türk Malları Haftası'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 16, title: null, start: '2025-12-22', end: '2025-12-26', belirli: ["Mehmet Akif Ersoy'u Anma Haftası"], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 17, title: null, start: '2025-12-29', end: '2026-01-02', belirli: ['Yılbaşı', 'Verem Eğitimi ve Propaganda Haftası'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Kulüp Raporu', 'Şeflik Raporu', 'Sınav Hazırla', 'Soru Üret'] },
  { w: 18, title: null, start: '2026-01-05', end: '2026-01-09', belirli: ['Enerji Tasarrufu Haftası', 'Çalışan Gazeteciler Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Öğretmen Ağı'] },
  { w: 19, title: '1. Dönem Bitişi', start: '2026-01-12', end: '2026-01-16', belirli: [], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Sınav Analizleri', 'Performans Değerlendir'] },
  { w: 20, title: 'Yarıyıl Tatili', start: '2026-01-19', end: '2026-01-30', belirli: [], ogretmen: [] },
  { w: 21, title: '2. Dönem Başlangıcı', start: '2026-02-02', end: '2026-02-06', belirli: ['Dünya Kanser Günü', 'Güvenli İnternet Günü'], ogretmen: ['Öğretmenler Kurulu', 'Zümre Tutanakları', 'Günlük Planlar', 'Kazanım Ara', 'Öğretmen Ağı'] },
  { w: 22, title: null, start: '2026-02-09', end: '2026-02-13', belirli: [], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 23, title: null, start: '2026-02-16', end: '2026-02-20', belirli: ['Sivil Savunma Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 24, title: null, start: '2026-02-23', end: '2026-02-27', belirli: ['Vergi Haftası', 'Yeşilay Haftası'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Sınav Hazırla', 'Soru Üret'] },
  { w: 25, title: null, start: '2026-03-02', end: '2026-03-06', belirli: ['Girişimcilik Haftası', 'Yeşilay Haftası', 'Dünya Kadınlar Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Veli Toplantıları', 'Öğretmen Ağı'] },
  { w: 26, title: null, start: '2026-03-09', end: '2026-03-13', belirli: ["Bilim ve Teknoloji Haftası", "İstiklâl Marşı'nın Kabulü ve Mehmet Akif Ersoy'u Anma Günü", "Çanakkale Zaferi ve Şehitleri Anma Günü"], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Sınav Analizleri', 'Performans Değerlendir'] },
  { w: 27, title: '2. Dönem Ara Tatili', start: '2026-03-16', end: '2026-03-20', belirli: ['Tüketiciyi Koruma Haftası', 'Türk Dünyası ve Toplulukları Haftası', 'Nevruz Bayramı'], ogretmen: [] },
  { w: 28, title: null, start: '2026-03-23', end: '2026-03-27', belirli: ['Orman Haftası', 'Dünya Meteoroloji Günü', 'Dünya Tiyatrolar Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 29, title: null, start: '2026-03-30', end: '2026-04-03', belirli: ['Kütüphaneler Haftası', 'Kanser Haftası', 'Dünya Otizm Farkındalık Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Kulüp Raporu', 'Şeflik Raporu'] },
  { w: 30, title: null, start: '2026-04-06', end: '2026-04-10', belirli: ['Kanser Haftası', 'Dünya Sağlık Günü', 'Kişisel Verileri Koruma Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Öğretmen Ağı'] },
  { w: 31, title: null, start: '2026-04-13', end: '2026-04-17', belirli: ['Turizm Haftası', 'Dünya Fikrî Mülkiyet Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 32, title: null, start: '2026-04-20', end: '2026-04-24', belirli: ['Ulusal Egemenlik ve Çocuk Bayramı'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 33, title: null, start: '2026-04-27', end: '2026-05-01', belirli: ["Kût'ül Amâre Zaferi", 'Emek ve Dayanışma Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Kulüp Raporu', 'Şeflik Raporu'] },
  { w: 34, title: null, start: '2026-05-04', end: '2026-05-08', belirli: ['Bilişim Haftası', 'Trafik ve İlkyardım Haftası', 'İş Sağlığı ve Güvenliği Haftası', 'Karayolu Trafik Güvenliği Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Öğretmen Ağı'] },
  { w: 35, title: null, start: '2026-05-11', end: '2026-05-15', belirli: ['Engelliler Haftası', 'Vakıflar Haftası', 'Anneler Günü', 'Aile Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 36, title: null, start: '2026-05-18', end: '2026-05-22', belirli: ["Müzeler Haftası", "Atatürk'ü Anma ve Gençlik ve Spor Bayramı"], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 37, title: null, start: '2026-05-25', end: '2026-05-29', belirli: ["Etik Günü", "İstanbul'un Fethi"], ogretmen: ['Günlük Planlar', 'Kazanım Ara'] },
  { w: 38, title: null, start: '2026-06-01', end: '2026-06-05', belirli: ['Hayat Boyu Öğrenme Haftası', 'Dünya Çevre Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Sınav Hazırla', 'Soru Üret', 'Öğretmen Ağı'] },
  { w: 39, title: '2. Dönem Bitişi (36. Hafta)', start: '2026-06-08', end: '2026-06-12', belirli: ['Çevre ve İklim Değişikliği Haftası', 'Babalar Günü'], ogretmen: ['Günlük Planlar', 'Kazanım Ara', 'Sınav Analizleri', 'Performans Değerlendir'] },
  { w: 40, title: 'Eğitim Öğretim Yılı Sonu Seminer Haftası', start: '2026-06-29', end: '2026-07-03', belirli: [], ogretmen: ['Öğretmenler Kurulu', 'Zümre Tutanakları', 'İdareye Teslim Evraklar', 'Kulüp Raporu', 'Şeflik Raporu'] },
];

/** Öğretmen işleri → path eşlemesi (route yoksa /evrak veya /dashboard) */
export const OGRETMEN_PATH: Record<string, string> = {
  'Günlük Planlar': '/evrak',
  'Kazanım Ara': '/evrak',
  'Öğretmen Ağı': '/profile',
  'Öğretmenler Kurulu': '/duty',
  'Zümre Tutanakları': '/evrak',
  'Yıllık Planlar': '/evrak',
  'BEP Programı': '/evrak',
  'Kulüp Planları': '/evrak',
  'Şeflik Planlar': '/evrak',
  'Kulüp Raporu': '/evrak',
  'Şeflik Raporu': '/evrak',
  'Sınav Hazırla': '/evrak',
  'Soru Üret': '/evrak',
  'Sınav Analizleri': '/evrak',
  'Performans Değerlendir': '/evrak',
  'Veli Toplantıları': '/evrak',
  'Proje Asistanı': '/evrak',
  'İdareye Teslim Evraklar': '/evrak',
  'Oyun Temelli Öğrenme': '/evrak',
  'Gelişim Takibi': '/evrak',
  'LGS Hazırlık ve Rehberlik': '/evrak',
  'YKS Hazırlık ve Rehberlik': '/evrak',
  'TYT-AYT Çalışmaları': '/evrak',
  'Staj ve İşyeri Eğitimi': '/evrak',
  'Mesleki Yeterlilik ve MYK': '/evrak',
  'Özel Eğitim BEP ve Raporlar': '/evrak',
  'Halk Eğitimi Kurs Planları': '/evrak',
  'BILSEM Özel Gelişim Programı': '/evrak',
  'İHL Pedagojik ve Değerler Etkinlikleri': '/evrak',
  'Okuma Yazma ve İlk Okuma': '/evrak',
  'Rehberlik ve Sosyal Beceri': '/evrak',
  'Tema Etkinliği ve Örnek': '/evrak',
  'Sınıf İçi Oyun ve Drama': '/evrak',
  'Meslek Atölyesi Uygulaması': '/evrak',
  'Alan Seçimi ve Yönlendirme': '/evrak',
  'Kurum Staj Değerlendirme': '/evrak',
  'Kültür ve Sanat Atölyesi': '/evrak',
  'Okuma Kültürü ve Kitap': '/evrak',
};
