/**
 * Kurum türüne ek Belirli Gün / Öğretmen işleri (2025-2026, w: 0–40).
 * Ortak şablona eklenir; MEB belirli gün/haftalar ve kademe pedagojisiyle uyumlu.
 */
import { SchoolType } from '../types/enums';

export type WeekExtra = { w: number; belirli: string[]; ogretmen: string[] };

const Wx = (w: number, belirli: string[], ogretmen: string[]): WeekExtra => ({ w, belirli, ogretmen });

/** Okul öncesi — oyun ve gelişim odaklı */
const AO = ['Oyun Temelli Öğrenme', 'Gelişim Takibi'];
const ao = (w: number, og: string[], bel: string[] = []) => Wx(w, bel, [...AO, ...og]);

const ANAOKUL: WeekExtra[] = [
  ao(0, ['Yıllık Planlar', 'BEP Programı', 'Veli Toplantıları'], ['Okul Öncesi Eğitim Haftası', 'Dünya Okul Öncesi Eğitim Günü']),
  ao(1, ['Tema Etkinliği ve Örnek', 'Sınıf İçi Oyun ve Drama'], []),
  ao(2, ['Sınıf İçi Oyun ve Drama', 'Kültür ve Sanat Atölyesi'], []),
  ao(3, ['Okuma Kültürü ve Kitap', 'Tema Etkinliği ve Örnek'], []),
  ao(4, ['Tema Etkinliği ve Örnek'], ['Oyun ve Oyuncak Haftası']),
  ao(5, ['Rehberlik ve Sosyal Beceri', 'Veli Toplantıları'], []),
  ao(6, ['Proje Asistanı', 'Kültür ve Sanat Atölyesi'], []),
  ao(7, ['Sınıf İçi Oyun ve Drama', 'Sınav Hazırla'], []),
  ao(8, ['Kültür ve Sanat Atölyesi', 'Veli Toplantıları'], []),
  ao(9, ['Rehberlik ve Sosyal Beceri', 'Performans Değerlendir'], []),
  ao(10, [], ['Güvenli Okul ve Farkındalık Haftası']),
  ao(11, ['Tema Etkinliği ve Örnek', 'Veli Toplantıları'], []),
  ao(12, [], ['Ağız ve Diş Sağlığı Haftası']),
  ao(13, ['Rehberlik ve Sosyal Beceri', 'BEP Programı'], []),
  ao(14, ['Kültür ve Sanat Atölyesi'], []),
  ao(15, ['Veli Toplantıları', 'Tema Etkinliği ve Örnek'], []),
  ao(16, ['Okuma Kültürü ve Kitap'], []),
  ao(17, ['Kulüp Raporu', 'Şeflik Raporu'], []),
  ao(18, ['Rehberlik ve Sosyal Beceri'], []),
  ao(19, ['Performans Değerlendir', 'Veli Toplantıları'], []),
  ao(21, ['Öğretmenler Kurulu', 'Zümre Tutanakları', 'Tema Etkinliği ve Örnek'], []),
  ao(22, ['Sınıf İçi Oyun ve Drama'], []),
  ao(23, [], ['Güvenli Okul ve Farkındalık Haftası']),
  ao(24, ['Proje Asistanı', 'Sınav Hazırla'], []),
  ao(25, ['Veli Toplantıları', 'Rehberlik ve Sosyal Beceri'], []),
  ao(26, ['Kültür ve Sanat Atölyesi', 'Proje Asistanı'], []),
  ao(27, ['Gelişim Takibi'], []),
  ao(28, ['Tema Etkinliği ve Örnek'], []),
  ao(29, ['BEP Programı', 'Veli Toplantıları'], []),
  ao(30, ['Rehberlik ve Sosyal Beceri'], []),
  ao(31, ['Okuma Kültürü ve Kitap'], []),
  ao(32, [], ['Ulusal Egemenlik ve Çocuk Bayramı']),
  ao(33, ['Kulüp Raporu', 'Veli Toplantıları'], []),
  ao(34, [], ['Güvenli Okul ve Farkındalık Haftası', 'Tema Etkinliği ve Örnek']),
  ao(35, ['Aile Günü'], []),
  ao(36, ['Kültür ve Sanat Atölyesi', 'Performans Değerlendir'], []),
  ao(37, ['Sınıf İçi Oyun ve Drama'], []),
  ao(38, [], ['Hayat Boyu Öğrenme Haftası']),
  ao(39, ['Veli Toplantıları', 'Gelişim Takibi'], []),
  ao(40, ['İdareye Teslim Evraklar', 'Kulüp Raporu'], []),
];

/** İlkokul — temel beceriler, okuma, veli iş birliği */
const ILKOKUL: WeekExtra[] = [
  Wx(0, [], ['Okuma Yazma ve İlk Okuma', 'Veli Toplantıları', 'Rehberlik ve Sosyal Beceri']),
  Wx(1, [], ['Okuma Kültürü ve Kitap', 'Tema Etkinliği ve Örnek', 'Proje Asistanı']),
  Wx(2, [], ['Okuma Yazma ve İlk Okuma', 'Kültür ve Sanat Atölyesi']),
  Wx(3, ['Türk Dil Bayramı'], ['Okuma Kültürü ve Kitap']),
  Wx(4, [], ['Rehberlik ve Sosyal Beceri', 'Veli Toplantıları']),
  Wx(5, [], ['Proje Asistanı', 'Kültür ve Sanat Atölyesi']),
  Wx(6, [], ['Okuma Yazma ve İlk Okuma']),
  Wx(7, [], ['Sınav Hazırla', 'Performans Değerlendir', 'Veli Toplantıları']),
  Wx(8, [], ['Kulüp Raporu', 'Okuma Kültürü ve Kitap']),
  Wx(9, [], ['Sınav Analizleri', 'Rehberlik ve Sosyal Beceri']),
  Wx(10, ['Güvenli Okul ve Farkındalık Haftası'], ['Rehberlik ve Sosyal Beceri', 'Veli Toplantıları']),
  Wx(11, [], ['Tema Etkinliği ve Örnek', 'Veli Toplantıları']),
  Wx(12, [], ['Okuma Kültürü ve Kitap', 'Proje Asistanı']),
  Wx(13, [], ['BEP Programı', 'Rehberlik ve Sosyal Beceri']),
  Wx(14, [], ['Kültür ve Sanat Atölyesi']),
  Wx(15, [], ['Veli Toplantıları', 'Okuma Yazma ve İlk Okuma']),
  Wx(16, [], ['Tema Etkinliği ve Örnek']),
  Wx(17, [], ['Kulüp Raporu', 'Şeflik Raporu', 'Veli Toplantıları']),
  Wx(18, [], ['Okuma Kültürü ve Kitap']),
  Wx(19, [], ['Sınav Analizleri', 'Performans Değerlendir', 'Rehberlik ve Sosyal Beceri']),
  Wx(21, [], ['Okuma Yazma ve İlk Okuma', 'Proje Asistanı', 'Veli Toplantıları']),
  Wx(22, [], ['Tema Etkinliği ve Örnek']),
  Wx(23, ['Güvenli Okul ve Farkındalık Haftası'], ['Rehberlik ve Sosyal Beceri']),
  Wx(24, [], ['Sınav Hazırla', 'Soru Üret', 'Veli Toplantıları']),
  Wx(25, [], ['Rehberlik ve Sosyal Beceri', 'Kültür ve Sanat Atölyesi']),
  Wx(26, [], ['Okuma Kültürü ve Kitap', 'Performans Değerlendir']),
  Wx(27, [], ['Okuma Yazma ve İlk Okuma']),
  Wx(28, [], ['Proje Asistanı', 'Veli Toplantıları']),
  Wx(29, [], ['BEP Programı', 'Kulüp Raporu']),
  Wx(30, [], ['Rehberlik ve Sosyal Beceri']),
  Wx(31, [], ['Okuma Kültürü ve Kitap', 'Tema Etkinliği ve Örnek']),
  Wx(32, [], ['Kültür ve Sanat Atölyesi', 'Veli Toplantıları']),
  Wx(33, [], ['Kulüp Raporu', 'Performans Değerlendir']),
  Wx(34, ['Güvenli İnternet Günü'], ['Rehberlik ve Sosyal Beceri']),
  Wx(35, [], ['Veli Toplantıları', 'Okuma Yazma ve İlk Okuma']),
  Wx(36, [], ['Tema Etkinliği ve Örnek', 'Kültür ve Sanat Atölyesi']),
  Wx(37, [], ['Proje Asistanı']),
  Wx(38, ['Hayat Boyu Öğrenme Haftası'], ['Okuma Kültürü ve Kitap', 'Veli Toplantıları']),
  Wx(39, [], ['Sınav Analizleri', 'Performans Değerlendir', 'Rehberlik ve Sosyal Beceri']),
  Wx(40, [], ['İdareye Teslim Evraklar', 'Veli Toplantıları']),
];

const LGS = ['LGS Hazırlık ve Rehberlik'];
const ORTAOKUL: WeekExtra[] = [
  Wx(0, [], [...LGS, 'Alan Seçimi ve Yönlendirme', 'Rehberlik ve Sosyal Beceri', 'Veli Toplantıları']),
  Wx(1, ['Rehberlik ve Kariyer Haftası'], ['Sınav Hazırla', 'Soru Üret', 'Okuma Kültürü ve Kitap']),
  Wx(2, [], [...LGS, 'Performans Değerlendir', 'Proje Asistanı']),
  Wx(3, [], [...LGS, 'Tema Etkinliği ve Örnek']),
  Wx(4, [], [...LGS, 'Kulüp Raporu', 'Veli Toplantıları']),
  Wx(5, [], [...LGS, 'Sınav Hazırla', 'Rehberlik ve Sosyal Beceri']),
  Wx(6, [], [...LGS, 'Kültür ve Sanat Atölyesi']),
  Wx(7, [], [...LGS, 'Sınav Hazırla', 'Soru Üret', 'Sınav Analizleri']),
  Wx(8, [], [...LGS, 'Veli Toplantıları', 'Performans Değerlendir']),
  Wx(9, [], [...LGS, 'Sınav Analizleri', 'Okuma Kültürü ve Kitap']),
  Wx(10, ['Güvenli Okul ve Farkındalık Haftası'], [...LGS]),
  Wx(11, [], [...LGS, 'Rehberlik ve Sosyal Beceri', 'Proje Asistanı']),
  Wx(12, [], [...LGS, 'Veli Toplantıları']),
  Wx(13, [], [...LGS, 'BEP Programı', 'Performans Değerlendir']),
  Wx(14, [], [...LGS, 'Kültür ve Sanat Atölyesi']),
  Wx(15, [], [...LGS, 'Tema Etkinliği ve Örnek']),
  Wx(16, [], [...LGS, 'Sınav Hazırla', 'Veli Toplantıları']),
  Wx(17, [], [...LGS, 'Kulüp Raporu', 'Şeflik Raporu']),
  Wx(18, [], [...LGS, 'Sınav Analizleri', 'Rehberlik ve Sosyal Beceri']),
  Wx(19, [], [...LGS, 'Sınav Analizleri', 'Performans Değerlendir', 'Veli Toplantıları']),
  Wx(21, [], [...LGS, 'Alan Seçimi ve Yönlendirme', 'Sınav Hazırla']),
  Wx(22, [], [...LGS, 'Okuma Kültürü ve Kitap']),
  Wx(23, ['Güvenli Okul ve Farkındalık Haftası'], [...LGS]),
  Wx(24, [], [...LGS, 'Soru Üret', 'Sınav Hazırla']),
  Wx(25, [], [...LGS, 'Veli Toplantıları', 'Proje Asistanı']),
  Wx(26, ['Çanakkale Zaferi ve Şehitleri Anma Günü'], [...LGS, 'Sınav Analizleri', 'Performans Değerlendir']),
  Wx(27, [], [...LGS, 'Rehberlik ve Sosyal Beceri']),
  Wx(28, [], [...LGS, 'Tema Etkinliği ve Örnek']),
  Wx(29, [], [...LGS, 'Kulüp Raporu', 'Veli Toplantıları']),
  Wx(30, [], [...LGS, 'Sınav Hazırla', 'Okuma Kültürü ve Kitap']),
  Wx(31, [], [...LGS, 'Kültür ve Sanat Atölyesi']),
  Wx(32, [], [...LGS, 'Veli Toplantıları', 'Performans Değerlendir']),
  Wx(33, [], [...LGS, 'Kulüp Raporu', 'Şeflik Raporu']),
  Wx(34, ['Bilişim Haftası'], [...LGS, 'Sınav Hazırla', 'Soru Üret']),
  Wx(35, [], [...LGS, 'Rehberlik ve Sosyal Beceri', 'Veli Toplantıları']),
  Wx(36, [], [...LGS, 'Performans Değerlendir', 'Kültür ve Sanat Atölyesi']),
  Wx(37, [], [...LGS, 'Proje Asistanı']),
  Wx(38, [], [...LGS, 'Sınav Hazırla', 'Soru Üret']),
  Wx(39, [], [...LGS, 'Sınav Analizleri', 'Performans Değerlendir']),
  Wx(40, [], [...LGS, 'İdareye Teslim Evraklar', 'Veli Toplantıları']),
];

const buildLise = (): WeekExtra[] =>
  ORTAOKUL.map((row) => {
    const og = row.ogretmen
      .filter((s) => s !== 'LGS Hazırlık ve Rehberlik')
      .concat(
        row.ogretmen.some((s) => s.includes('LGS') || s === 'LGS Hazırlık ve Rehberlik')
          ? ['YKS Hazırlık ve Rehberlik', 'TYT-AYT Çalışmaları']
          : [],
      );
    const uniq = [...new Set(og)];
    return { w: row.w, belirli: row.belirli, ogretmen: uniq };
  });

const MESLEK: WeekExtra[] = [
  Wx(0, ['Meslek Tanıtım ve İşyeri Gezisi Haftası'], ['Meslek Atölyesi Uygulaması', 'Mesleki Yeterlilik ve MYK', 'Veli Toplantıları']),
  Wx(1, [], ['Meslek Eğitimi ve Teknoloji Haftası', 'Staj ve İşyeri Eğitimi', 'Rehberlik ve Sosyal Beceri']),
  Wx(2, [], ['Meslek Atölyesi Uygulaması', 'Kurum Staj Değerlendirme']),
  Wx(3, [], ['Mesleki Yeterlilik ve MYK', 'Okuma Kültürü ve Kitap']),
  Wx(4, ['İş Sağlığı ve Güvenliği Haftası'], ['Meslek Atölyesi Uygulaması', 'Veli Toplantıları']),
  Wx(5, ['Meslek Eğitimi ve Teknoloji Haftası'], ['Mesleki Yeterlilik ve MYK', 'Proje Asistanı']),
  Wx(6, [], ['Staj ve İşyeri Eğitimi', 'Kültür ve Sanat Atölyesi']),
  Wx(7, [], ['Sınav Hazırla', 'Meslek Atölyesi Uygulaması', 'YKS Hazırlık ve Rehberlik']),
  Wx(8, [], ['Kulüp Raporu', 'Mesleki Yeterlilik ve MYK']),
  Wx(9, [], ['Sınav Analizleri', 'Kurum Staj Değerlendirme']),
  Wx(10, ['Güvenli Okul ve Farkındalık Haftası'], ['Staj ve İşyeri Eğitimi', 'Meslek Atölyesi Uygulaması']),
  Wx(11, [], ['Veli Toplantıları', 'Meslek Atölyesi Uygulaması']),
  Wx(12, [], ['BEP Programı', 'Rehberlik ve Sosyal Beceri']),
  Wx(13, [], ['Mesleki Yeterlilik ve MYK', 'Performans Değerlendir']),
  Wx(14, [], ['Kültür ve Sanat Atölyesi']),
  Wx(15, [], ['Staj ve İşyeri Eğitimi', 'Veli Toplantıları']),
  Wx(16, [], ['Meslek Atölyesi Uygulaması']),
  Wx(17, [], ['Kulüp Raporu', 'Şeflik Raporu', 'Kurum Staj Değerlendirme']),
  Wx(18, [], ['Sınav Analizleri', 'Mesleki Yeterlilik ve MYK']),
  Wx(19, [], ['Performans Değerlendir', 'YKS Hazırlık ve Rehberlik']),
  Wx(21, ['Meslek Tanıtım ve İşyeri Gezisi Haftası'], ['Staj ve İşyeri Eğitimi', 'Meslek Atölyesi Uygulaması']),
  Wx(22, [], ['Mesleki Yeterlilik ve MYK']),
  Wx(23, ['Güvenli Okul ve Farkındalık Haftası'], ['Meslek Atölyesi Uygulaması', 'Rehberlik ve Sosyal Beceri']),
  Wx(24, [], ['Sınav Hazırla', 'Soru Üret', 'Meslek Atölyesi Uygulaması']),
  Wx(25, [], ['Veli Toplantıları', 'Kurum Staj Değerlendirme']),
  Wx(26, ['Bilim ve Teknoloji Haftası'], ['Meslek Atölyesi Uygulaması', 'Proje Asistanı']),
  Wx(27, [], ['Staj ve İşyeri Eğitimi']),
  Wx(28, [], ['Mesleki Yeterlilik ve MYK', 'Okuma Kültürü ve Kitap']),
  Wx(29, [], ['Kulüp Raporu', 'Veli Toplantıları']),
  Wx(30, [], ['Performans Değerlendir', 'Rehberlik ve Sosyal Beceri']),
  Wx(31, ['Turizm Haftası'], ['Meslek Atölyesi Uygulaması', 'Veli Toplantıları']),
  Wx(32, [], ['Veli Toplantıları', 'Kültür ve Sanat Atölyesi']),
  Wx(33, [], ['Kulüp Raporu', 'Şeflik Raporu']),
  Wx(34, ['Çıraklık ve İşletmelerde Meslek Eğitimi Haftası'], ['Staj ve İşyeri Eğitimi', 'Kurum Staj Değerlendirme', 'İş Sağlığı ve Güvenliği Haftası']),
  Wx(35, [], ['Mesleki Yeterlilik ve MYK', 'Veli Toplantıları']),
  Wx(36, ["Atatürk'ü Anma ve Gençlik ve Spor Bayramı"], ['Meslek Atölyesi Uygulaması', 'Kültür ve Sanat Atölyesi']),
  Wx(37, [], ['Proje Asistanı', 'Performans Değerlendir']),
  Wx(38, ['Hayat Boyu Öğrenme Haftası'], ['Mesleki Yeterlilik ve MYK', 'Staj ve İşyeri Eğitimi', 'Veli Toplantıları']),
  Wx(39, [], ['Sınav Analizleri', 'Kurum Staj Değerlendirme']),
  Wx(40, [], ['Mesleki Yeterlilik ve MYK', 'İdareye Teslim Evraklar']),
];

const IHL_O: WeekExtra[] = ORTAOKUL.map((row) => ({
  w: row.w,
  belirli: row.w === 2 ? ['İmam Hatip Okulları Etkinlik ve Değerler Haftası', ...row.belirli] : row.belirli,
  ogretmen: [...new Set([...row.ogretmen.filter((s) => s !== 'Alan Seçimi ve Yönlendirme'), 'İHL Pedagojik ve Değerler Etkinlikleri'])],
}));

const IHL_L: WeekExtra[] = buildLise().map((row) => ({
  w: row.w,
  belirli: row.w === 2 ? ['İmam Hatip Okulları Etkinlik ve Değerler Haftası', ...row.belirli] : row.belirli,
  ogretmen: [...new Set([...row.ogretmen, 'İHL Pedagojik ve Değerler Etkinlikleri'])],
}));

const OZEL: WeekExtra[] = [
  Wx(0, ['Kaynaştırma ve Özel Eğitim Haftası'], ['Özel Eğitim BEP ve Raporlar', 'BEP Programı', 'Rehberlik ve Sosyal Beceri', 'Veli Toplantıları']),
  Wx(1, [], ['Özel Eğitim BEP ve Raporlar', 'Performans Değerlendir', 'Veli Toplantıları']),
  Wx(2, [], ['Özel Eğitim BEP ve Raporlar', 'Kültür ve Sanat Atölyesi']),
  Wx(3, [], ['Özel Eğitim BEP ve Raporlar', 'Okuma Kültürü ve Kitap']),
  Wx(4, ['Kaynaştırma ve Özel Eğitim Haftası'], ['Özel Eğitim BEP ve Raporlar', 'Rehberlik ve Sosyal Beceri']),
  Wx(5, [], ['Özel Eğitim BEP ve Raporlar', 'Proje Asistanı']),
  Wx(6, [], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları']),
  Wx(7, [], ['Özel Eğitim BEP ve Raporlar', 'Sınav Hazırla', 'Performans Değerlendir']),
  Wx(8, [], ['Özel Eğitim BEP ve Raporlar', 'Kulüp Raporu']),
  Wx(9, [], ['Özel Eğitim BEP ve Raporlar', 'Sınav Analizleri']),
  Wx(10, ['Güvenli Okul ve Farkındalık Haftası'], ['Özel Eğitim BEP ve Raporlar', 'Rehberlik ve Sosyal Beceri']),
  Wx(11, [], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları', 'Tema Etkinliği ve Örnek']),
  Wx(12, ['Dünya Engelliler Günü'], ['Özel Eğitim BEP ve Raporlar', 'Rehberlik ve Sosyal Beceri']),
  Wx(13, [], ['Özel Eğitim BEP ve Raporlar', 'BEP Programı']),
  Wx(14, [], ['Özel Eğitim BEP ve Raporlar', 'Kültür ve Sanat Atölyesi']),
  Wx(15, [], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları']),
  Wx(16, [], ['Özel Eğitim BEP ve Raporlar']),
  Wx(17, [], ['Özel Eğitim BEP ve Raporlar', 'Kulüp Raporu', 'Şeflik Raporu']),
  Wx(18, [], ['Özel Eğitim BEP ve Raporlar', 'Rehberlik ve Sosyal Beceri']),
  Wx(19, [], ['Özel Eğitim BEP ve Raporlar', 'Performans Değerlendir', 'Veli Toplantıları']),
  Wx(21, [], ['Özel Eğitim BEP ve Raporlar', 'Proje Asistanı', 'Veli Toplantıları']),
  Wx(22, [], ['Özel Eğitim BEP ve Raporlar', 'Tema Etkinliği ve Örnek']),
  Wx(23, ['Güvenli Okul ve Farkındalık Haftası'], ['Özel Eğitim BEP ve Raporlar']),
  Wx(24, [], ['Özel Eğitim BEP ve Raporlar', 'Sınav Hazırla', 'Soru Üret']),
  Wx(25, [], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları']),
  Wx(26, [], ['Özel Eğitim BEP ve Raporlar', 'Performans Değerlendir', 'Sınav Analizleri']),
  Wx(27, [], ['Özel Eğitim BEP ve Raporlar']),
  Wx(28, [], ['Özel Eğitim BEP ve Raporlar', 'Okuma Kültürü ve Kitap']),
  Wx(29, ['Dünya Otizm Farkındalık Günü'], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları', 'Kulüp Raporu']),
  Wx(30, [], ['Özel Eğitim BEP ve Raporlar', 'Rehberlik ve Sosyal Beceri']),
  Wx(31, [], ['Özel Eğitim BEP ve Raporlar', 'Kültür ve Sanat Atölyesi']),
  Wx(32, [], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları']),
  Wx(33, [], ['Özel Eğitim BEP ve Raporlar', 'Kulüp Raporu', 'Şeflik Raporu']),
  Wx(34, ['Bilişim Haftası'], ['Özel Eğitim BEP ve Raporlar', 'Rehberlik ve Sosyal Beceri']),
  Wx(35, ['Engelliler Haftası'], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları']),
  Wx(36, [], ['Özel Eğitim BEP ve Raporlar', 'Performans Değerlendir']),
  Wx(37, [], ['Özel Eğitim BEP ve Raporlar', 'Proje Asistanı']),
  Wx(38, ['Hayat Boyu Öğrenme Haftası'], ['Özel Eğitim BEP ve Raporlar', 'Veli Toplantıları']),
  Wx(39, [], ['Özel Eğitim BEP ve Raporlar', 'Sınav Analizleri']),
  Wx(40, [], ['Özel Eğitim BEP ve Raporlar', 'İdareye Teslim Evraklar']),
];

const HALK: WeekExtra[] = [
  Wx(0, ['Halk Eğitimi ve Kurs Haftası', 'Hayat Boyu Öğrenme Haftası'], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(1, [], ['Halk Eğitimi Kurs Planları', 'Rehberlik ve Sosyal Beceri']),
  Wx(2, [], ['Halk Eğitimi Kurs Planları', 'Okuma Kültürü ve Kitap']),
  Wx(3, [], ['Halk Eğitimi Kurs Planları', 'Proje Asistanı']),
  Wx(4, [], ['Halk Eğitimi Kurs Planları', 'Kültür ve Sanat Atölyesi']),
  Wx(5, [], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(6, [], ['Halk Eğitimi Kurs Planları', 'Tema Etkinliği ve Örnek']),
  Wx(7, [], ['Halk Eğitimi Kurs Planları', 'Performans Değerlendir']),
  Wx(8, [], ['Halk Eğitimi Kurs Planları', 'Kulüp Raporu']),
  Wx(9, [], ['Halk Eğitimi Kurs Planları', 'Sınav Analizleri']),
  Wx(10, ['Güvenli Okul ve Farkındalık Haftası'], ['Halk Eğitimi Kurs Planları']),
  Wx(11, [], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(12, [], ['Halk Eğitimi Kurs Planları', 'Okuma Kültürü ve Kitap']),
  Wx(13, [], ['Halk Eğitimi Kurs Planları', 'BEP Programı']),
  Wx(14, [], ['Halk Eğitimi Kurs Planları', 'Kültür ve Sanat Atölyesi']),
  Wx(15, [], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(16, [], ['Halk Eğitimi Kurs Planları']),
  Wx(17, [], ['Halk Eğitimi Kurs Planları', 'Kulüp Raporu', 'Şeflik Raporu']),
  Wx(18, [], ['Halk Eğitimi Kurs Planları', 'Rehberlik ve Sosyal Beceri']),
  Wx(19, [], ['Halk Eğitimi Kurs Planları', 'Performans Değerlendir']),
  Wx(21, ['Hayat Boyu Öğrenme Haftası'], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(22, [], ['Halk Eğitimi Kurs Planları', 'Tema Etkinliği ve Örnek']),
  Wx(23, ['Güvenli Okul ve Farkındalık Haftası'], ['Halk Eğitimi Kurs Planları']),
  Wx(24, [], ['Halk Eğitimi Kurs Planları', 'Sınav Hazırla']),
  Wx(25, [], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(26, ['Bilim ve Teknoloji Haftası'], ['Halk Eğitimi Kurs Planları', 'Proje Asistanı']),
  Wx(27, [], ['Halk Eğitimi Kurs Planları']),
  Wx(28, [], ['Halk Eğitimi Kurs Planları', 'Okuma Kültürü ve Kitap']),
  Wx(29, [], ['Halk Eğitimi Kurs Planları', 'Kulüp Raporu']),
  Wx(30, [], ['Halk Eğitimi Kurs Planları', 'Rehberlik ve Sosyal Beceri']),
  Wx(31, ['Turizm Haftası'], ['Halk Eğitimi Kurs Planları']),
  Wx(32, [], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(33, [], ['Halk Eğitimi Kurs Planları', 'Kulüp Raporu']),
  Wx(34, ['Bilişim Haftası'], ['Halk Eğitimi Kurs Planları']),
  Wx(35, [], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(36, [], ['Halk Eğitimi Kurs Planları', 'Kültür ve Sanat Atölyesi']),
  Wx(37, [], ['Halk Eğitimi Kurs Planları', 'Proje Asistanı']),
  Wx(38, ['Hayat Boyu Öğrenme Haftası', 'Dünya Çevre Günü'], ['Halk Eğitimi Kurs Planları', 'Veli Toplantıları']),
  Wx(39, [], ['Halk Eğitimi Kurs Planları', 'Performans Değerlendir']),
  Wx(40, [], ['Halk Eğitimi Kurs Planları', 'İdareye Teslim Evraklar']),
];

const BILSEM_W: WeekExtra[] = [
  Wx(0, ['BILSEM ve Özel Yetenek Etkinlik Haftası'], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı', 'Veli Toplantıları']),
  Wx(1, ['Okuma Kültürü ve Kitap Haftası'], ['BILSEM Özel Gelişim Programı', 'Okuma Kültürü ve Kitap', 'Kültür ve Sanat Atölyesi']),
  Wx(2, [], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı', 'Okuma Kültürü ve Kitap']),
  Wx(3, [], ['BILSEM Özel Gelişim Programı', 'Tema Etkinliği ve Örnek']),
  Wx(4, [], ['BILSEM Özel Gelişim Programı', 'Rehberlik ve Sosyal Beceri']),
  Wx(5, [], ['BILSEM Özel Gelişim Programı', 'Kulüp Raporu']),
  Wx(6, [], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı', 'Performans Değerlendir']),
  Wx(7, [], ['BILSEM Özel Gelişim Programı', 'Sınav Hazırla', 'Soru Üret']),
  Wx(8, [], ['BILSEM Özel Gelişim Programı', 'Veli Toplantıları', 'Kültür ve Sanat Atölyesi']),
  Wx(9, [], ['BILSEM Özel Gelişim Programı', 'Sınav Analizleri']),
  Wx(10, ['Güvenli Okul ve Farkındalık Haftası'], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı']),
  Wx(11, [], ['BILSEM Özel Gelişim Programı', 'Tema Etkinliği ve Örnek']),
  Wx(12, [], ['BILSEM Özel Gelişim Programı', 'Okuma Kültürü ve Kitap']),
  Wx(13, [], ['BILSEM Özel Gelişim Programı', 'Rehberlik ve Sosyal Beceri']),
  Wx(14, [], ['BILSEM Özel Gelişim Programı', 'Kültür ve Sanat Atölyesi']),
  Wx(15, [], ['BILSEM Özel Gelişim Programı', 'Veli Toplantıları']),
  Wx(16, [], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı']),
  Wx(17, [], ['BILSEM Özel Gelişim Programı', 'Kulüp Raporu', 'Şeflik Raporu']),
  Wx(18, [], ['BILSEM Özel Gelişim Programı', 'Performans Değerlendir']),
  Wx(19, [], ['BILSEM Özel Gelişim Programı', 'Sınav Analizleri', 'Veli Toplantıları']),
  Wx(21, ['BILSEM ve Özel Yetenek Etkinlik Haftası'], ['BILSEM Özel Gelişim Programı', 'Alan Seçimi ve Yönlendirme']),
  Wx(22, [], ['BILSEM Özel Gelişim Programı', 'Tema Etkinliği ve Örnek']),
  Wx(23, ['Güvenli Okul ve Farkındalık Haftası'], ['BILSEM Özel Gelişim Programı']),
  Wx(24, [], ['BILSEM Özel Gelişim Programı', 'Sınav Hazırla', 'Soru Üret']),
  Wx(25, [], ['BILSEM Özel Gelişim Programı', 'Veli Toplantıları', 'Proje Asistanı']),
  Wx(26, ['Bilim ve Teknoloji Haftası'], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı', 'Performans Değerlendir']),
  Wx(27, [], ['BILSEM Özel Gelişim Programı']),
  Wx(28, [], ['BILSEM Özel Gelişim Programı', 'Okuma Kültürü ve Kitap']),
  Wx(29, [], ['BILSEM Özel Gelişim Programı', 'Kulüp Raporu', 'Veli Toplantıları']),
  Wx(30, [], ['BILSEM Özel Gelişim Programı', 'Rehberlik ve Sosyal Beceri']),
  Wx(31, [], ['BILSEM Özel Gelişim Programı', 'Kültür ve Sanat Atölyesi']),
  Wx(32, ['Ulusal Egemenlik ve Çocuk Bayramı'], ['BILSEM Özel Gelişim Programı', 'Kültür ve Sanat Atölyesi']),
  Wx(33, [], ['BILSEM Özel Gelişim Programı', 'Kulüp Raporu']),
  Wx(34, ['Bilişim Haftası'], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı']),
  Wx(35, [], ['BILSEM Özel Gelişim Programı', 'Veli Toplantıları']),
  Wx(36, [], ['BILSEM Özel Gelişim Programı', 'Kültür ve Sanat Atölyesi', 'Performans Değerlendir']),
  Wx(37, [], ['BILSEM Özel Gelişim Programı', 'Proje Asistanı']),
  Wx(38, ['Hayat Boyu Öğrenme Haftası', 'Dünya Çevre Günü'], ['BILSEM Özel Gelişim Programı', 'Veli Toplantıları']),
  Wx(39, [], ['BILSEM Özel Gelişim Programı', 'Sınav Analizleri']),
  Wx(40, [], ['BILSEM Özel Gelişim Programı', 'İdareye Teslim Evraklar']),
];

const LISE_FAMILY = buildLise();

export const ACADEMIC_CALENDAR_TYPE_EXTRAS_2025_2026: Partial<Record<SchoolType, WeekExtra[]>> = {
  [SchoolType.anaokul]: ANAOKUL,
  [SchoolType.ilkokul]: ILKOKUL,
  [SchoolType.ortaokul]: ORTAOKUL,
  [SchoolType.temel_egitim]: ORTAOKUL,
  [SchoolType.lise]: LISE_FAMILY,
  [SchoolType.meslek_lisesi]: MESLEK,
  [SchoolType.fen_lisesi]: LISE_FAMILY,
  [SchoolType.sosyal_bilimler_lisesi]: LISE_FAMILY,
  [SchoolType.anadolu_lisesi]: LISE_FAMILY,
  [SchoolType.cok_programli_anadolu_lisesi]: LISE_FAMILY,
  [SchoolType.acik_ogretim_lisesi]: LISE_FAMILY,
  [SchoolType.guzel_sanatlar_lisesi]: LISE_FAMILY,
  [SchoolType.spor_lisesi]: LISE_FAMILY,
  [SchoolType.imam_hatip_ortaokul]: IHL_O,
  [SchoolType.imam_hatip_lise]: IHL_L,
  [SchoolType.ozel_egitim]: OZEL,
  [SchoolType.ozel_egitim_uygulama_merkezi]: OZEL,
  [SchoolType.halk_egitim]: HALK,
  [SchoolType.rehberlik_merkezi]: HALK,
  [SchoolType.ogretmenevi_aksam_sanat]: HALK,
  [SchoolType.mesleki_egitim_merkezi]: HALK,
  [SchoolType.bilsem]: BILSEM_W,
};
